### ISSUE TITLE
For keras model, load_weights() cannot happen before generate function

### ISSUE THREAD

**Issue by cloudseasail** [tensorflow/cleverhans#1001]
**Describe the bug**
For keras model,  if I load the pretrained weights ahead of adv generate function,  there is Error with "uninitialized weight".  
So I have to load weights after that,  I donot understand why there is dependece here. 

**To Reproduce**
Bad case,  with load_weights ahead of fgsm.generate()
```
keras_model.load_weights("weight.h5")
model = KerasModelWrapper(keras_model)
with tf.Session() as sess
    fgsm = FastGradientMethod(model, sess=sess)
    fgsm_params = {'eps': 0.3,'clip_min': -1., 'clip_max': 1.}
    adv_x = fgsm.generate(x, **fgsm_params)
    sess.run(adv_x)
```

Good case,  with load_weights after of fgsm.generate()
```
model = KerasModelWrapper(keras_model)
with tf.Session() as sess
    fgsm = FastGradientMethod(model, sess=sess)
    fgsm_params = {'eps': 0.3,'clip_min': -1., 'clip_max': 1.}
    adv_x = fgsm.generate(x, **fgsm_params)
    keras_model.load_weights("weight.h5")   
    sess.run(adv_x)
```

**Comment by HaojieYuan** [comment]
That's due to your session.
You specified a new session after load keras model with keras default session.
The bad case can be modified as:
```
keras_model.load_weights("weight.h5")
model = KerasModelWrapper(keras_model)

sess = tf.keras.backend.get_session()
fgsm = FastGradientMethod(model, sess=sess)
fgsm_params = {'eps': 0.3,'clip_min': -1., 'clip_max': 1.}
adv_x = fgsm.generate(x, **fgsm_params)
sess.run(adv_x)
```

**Comment by cloudseasail** [comment]
> That's due to your session.
> You specified a new session after load keras model with keras default session.
> The bad case can be modified as:
> 
> ```
> keras_model.load_weights("weight.h5")
> model = KerasModelWrapper(keras_model)
> 
> sess = tf.keras.backend.get_session()
> fgsm = FastGradientMethod(model, sess=sess)
> fgsm_params = {'eps': 0.3,'clip_min': -1., 'clip_max': 1.}
> adv_x = fgsm.generate(x, **fgsm_params)
> sess.run(adv_x)
> ```

I think you are right,  that is in different session,  thanks for the quick response!
