### ISSUE TITLE
Support for PyTorch v1.0

### ISSUE THREAD

**Issue by michaelshiyu** [tensorflow/cleverhans#1017]
PyTorch v1.0 has been around for a while, any thoughts on upgrading the PyTorch support from v0.4 to v1.0?

**Comment by michaelshiyu** [comment]
If we're to support PyTorch v1.0, I can take this issue if nobody else is.

**Comment by npapernot** [comment]
We've just started a major redesign of CleverHans to support PyTorch as well as TF2 and JAX. Let us know if you'd like to help us with that

See #1018

**Comment by michaelshiyu** [comment]
@npapernot I’m more than happy to contribute! Do you have anything specific that needs help right now? If not I guess I can start by implementing attacks in PyTorch and put them in future/attacks?

**Comment by npapernot** [comment]
We are planning to first implement PGD in each framework, including PyTorch. If you'd like to help with this, that would be great! The correspond issue to track this is #1020

**Comment by npapernot** [comment]
I'll close this given that we are tracking progress on #1020, thanks @michaelshiyu
