### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [tensorflow/cleverhans#1031]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by npapernot** [comment]
Thanks for the report. The current travis configuration does not specify sudo:false but rather sudo:required so we will keep that configuration for now.

**Comment by cclauss** [comment]
The article makes it clear that the __sudo__ tag is now fully deprecated because the __sudo__ command is _always_ available and there is no way to turn it off.
