### ISSUE TITLE
No jsma_batch function  in cleverhans.attacks_tf

### ISSUE THREAD

**Issue by zscsg** [tensorflow/cleverhans#1042]
Dear authors,
       Firstly i want to thank you, cleverhans is  a very wonderful library. It is very useful, and I learned a lot from it. But when i read the source code, the implementation of SaliencyMapMethod imports jsma_batch from cleverhans.attacks_tf, but i search the attacks_tf.py， there is no such a function in it. But i find a similar one named jsma. So i test SaliencyMapMethod setting symbolic_impl=False. And it return errors " cannot import name 'jsma_batch", I think maybe jsma is supposed to be imported in the implementation of SaliencyMapMethod, not jsma_batch. It is a clerical error. I hope this can be helpful for you. Thank you for your wonderful contribution! Cleverhans version is 3.0.1!
                                                                                                                        My best regards

**Comment by npapernot** [comment]
Thanks for raising this issue. Did the library raise the following error when you tried to set symbolic_impl to False? 

https://github.com/tensorflow/cleverhans/blob/a79eda0bc3b23ff9ce7a42726902b36346d5c25f/cleverhans/attacks/saliency_map_method.py#L84

**Comment by zscsg** [comment]
No, sir, it doesn't raise such an error.

**Comment by npapernot** [comment]
Are you using the last version of CleverHans? Specifically, did you clone from the repo or install via pip?
