### ISSUE TITLE
Issue creating a CarliniWagnerL2 attack

### ISSUE THREAD

**Issue by shamoons** [tensorflow/cleverhans#1044]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
I am attempting to do a simple CarliniWagnerL2 attack on some images.

**To Reproduce**
My code is as follow:
```
file_list = glob.glob("images/*.jpg")
for image_path in file_list:
    img = image.load_img(image_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = x.astype('float32')
    x /= 255

    X.append(x)

target = [np.zeros((1000,))]
target[0][0] = 1
target = np.repeat(target, len(X), axis=0)
params = {
    'max_iterations': 1000,
    'binary_search_steps': 3,
    'initial_const': 1,
    'clip_min': -5,
    'clip_max': 5,
    'batch_size': 1,
    'y_target': target
}

X = np.array(X)

x_tensor = K.variable(X)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    fgsm = CarliniWagnerL2(wrap, sess=sess)
    adv = fgsm.generate(x_tensor, **params)
```

This takes some time, but then gives an error:
```
/Users/shamoon/.local/share/virtualenvs/adversarial-exploration-dPMp-7ya/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/shamoon/.local/share/virtualenvs/adversarial-exploration-dPMp-7ya/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Expected behavior**
Attack images to be created

**System configuration**
 - OS (Mac OS)
 - Python version (3.7.2)
 - TensorFlow version (1.13)

**Comment by carlini** [comment]
I'm not sure that I can debug this from the error you've given. Do you have a longer stack trace? Could you try it on exactly one image and report the intermediate results?

**Comment by npapernot** [comment]
If you are still facing this issue, feel free to re-open it with additional information requested (e.g., stack trace, or your model definition)
