### ISSUE TITLE
C&W attack on inceptionv3

### ISSUE THREAD

**Issue by xubo0321** [tensorflow/cleverhans#1065]
I want to generate adversarial examples with C&WL2 on the inceptionv3, but it appeers the error as follows:
[INFO 2019-06-06 21:09:06,138 cleverhans] Constructing new graph for attack CarliniWagnerL2
Traceback (most recent call last):
  File "cw/cw_inceptionv3.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "cw/cw_inceptionv3.py", line 139, in main
    x_adv = cwl2.generate_np(x_input,**cw_params)
  File "/home/ra/cleverhans/cleverhans/attacks/attack.py", line 185, in generate_np
    self.construct_graph(fixed, feedable, x_val, hash_key)
  File "/home/ra/cleverhans/cleverhans/attacks/attack.py", line 157, in construct_graph
    x_adv = self.generate(x, **new_kwargs)
  File "/home/ra/cleverhans/cleverhans/attacks/carlini_wagner_l2.py", line 70, in generate
    labels, nb_classes = self.get_or_guess_labels(x, kwargs)
  File "/home/ra/cleverhans/cleverhans/attacks/attack.py", line 277, in get_or_guess_labels
    preds = self.model.get_probs(x)
  File "/home/ra/cleverhans/cleverhans/model.py", line 84, in get_probs
    d = self.fprop(x, **kwargs)
  File "/home/ra/cleverhans/cleverhans/model.py", line 108, in fprop
    raise NotImplementedError('`fprop` not implemented.')
NotImplementedError: `fprop` not implemented.

and the the executable file is as follows:

"""My changed full source code."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import warnings
warnings.filterwarnings('ignore')
import sys
sys.path.append('/home/ra/cleverhans/')
from io import BytesIO
import numpy as np
import tensorflow as tf
from tensorflow.contrib.slim.nets import inception
from PIL import Image
from scipy.misc import imsave,imread
from cleverhans.model import Model
from cleverhans.attacks import CarliniWagnerL2

slim = tf.contrib.slim

def load_images(input_dir, batch_shape):
  """Read png images from input directory in batches.
  Args:
    input_dir: input directory
    batch_shape: shape of minibatch array, i.e. [batch_size, height, width, 3]
  Yields:
    filenames: list file names without path of each image
      Lenght of this list could be less than batch_size, in this case only
      first few images of the result are elements of the minibatch.
    images: array with all images from this batch
  """
  images = np.zeros(batch_shape)
  filenames = []
  idx = 0
  batch_size = batch_shape[0]
  for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
    print(filepath)
   # --- change open method . This change has no impact for code ---
    with open(filepath,"rb") as f:
      image = np.array(Image.open(f).convert('RGB')).astype(np.float) / 255.0
    # Images for inception classifier are normalized to be in [-1, 1] interval.
    images[idx, :, :, :] = image * 2.0 - 1.0
    filenames.append(os.path.basename(filepath))
    idx += 1
    if idx == batch_size:
      yield filenames, images
      filenames = []
      images = np.zeros(batch_shape)
      idx = 0
  if idx > 0:
    yield filenames, images

def save_images(images, filenames, output_dir):
  """Saves images to the output directory.
  Args:
    images: array with minibatch of images
    filenames: list of filenames without path
      If number of file names in this list less than number of images in
      the minibatch then only first len(filenames) images will be saved.
    output_dir: directory where to save images
  """
  for i, filename in enumerate(filenames):
    # Images for inception classifier are normalized to be in [-1, 1] interval,
    # so rescale them back to [0, 1].
    with tf.gfile.Open(os.path.join(output_dir, filename), 'w') as f:
      img = (((images[i, :, :, :] + 1.0) * 0.5) * 255.0).astype(np.uint8)
      Image.fromarray(img).save(f, format='PNG')

# ---change Model from object---
class InceptionModel(Model):
  """Model class for CleverHans library."""

  def __init__(self, nb_classes):
    super(InceptionModel, self).__init__(nb_classes=nb_classes,
                                         needs_dummy_fprop=True)
    self.built = False

  def __call__(self, x_input, return_logits=False):
    """Constructs model and return probabilities for given input."""
    reuse = True if self.built else None
    with slim.arg_scope(inception.inception_v3_arg_scope()):
      # Inception preprocessing uses [-1, 1]-scaled input.
      x_input = x_input * 2.0 - 1.0
      _, end_points = inception.inception_v3(
          x_input, num_classes=self.nb_classes, is_training=False,
          reuse=reuse)
    self.built = True
   # self.logits = end_points['Logits']
    # Strip off the extra reshape op at the output
    self.probs = end_points['Predictions'].op.inputs[0]
    if return_logits:
      return self.logits
    else:
      return self.probs

 # def get_logits(self, x_input):
  #  return self(x_input, return_logits=True)

 # def get_probs(self, x_input):
  #  return self(x_input)

def main(_):
  """Run the sample attack"""
  # Images for inception classifier are normalized to be in [-1, 1] interval,
  # eps is a difference between pixels so it should be in [0, 2] interval.
  # Renormalizing epsilon from [0, 255] to [0, 2].
  tensorflow_master = ""
  checkpoint_path   = "/home/ra/cleverhans/cw/inception_v3.ckpt"
  input_dir         = "/home/ra/cleverhans/cw/tmp"
  output_dir        = "/home/ra/cleverhans/cw"
  image_width       = 299
  image_height      = 299
  batch_size        = 50
  nb_classes=1001
  cw_params = {'batch_size': 1,
             'confidence': 10,
             'learning_rate': 0.1,
             'binary_search_steps': 5,
             'max_iterations': 1000,
             'abort_early': True,
             'initial_const': 0.01,
             'clip_min': 0,
             'clip_max': 1}
  batch_shape = [batch_size, image_height, image_width, 3]
  tf.logging.set_verbosity(tf.logging.INFO)
  with tf.Graph().as_default():
    # Prepare graph
    x_input = tf.placeholder(tf.float32, shape=batch_shape)
    model = InceptionModel(nb_classes)
    ses = tf.Session()
    cwl2 = CarliniWagnerL2(model,ses)
    x_adv = cwl2.generate_np(x_input,**cw_params)
    sess.run(tf.global_variables_initializer())
    
  #  save_images(x_adv, filenames, output_dir)
    # Run computation
    saver = tf.train.Saver(slim.get_model_variables())
 #   adv_images = sess.run(x_adv, feed_dict={x_input: images})
  #  save_images(adv_images, filenames, output_dir)
    session_creator = tf.train.ChiefSessionCreator(
        scaffold=tf.train.Scaffold(saver=saver),
        checkpoint_filename_with_path=checkpoint_path,
        master=tensorflow_master)
    with tf.train.MonitoredSession(session_creator=session_creator) as sess:
      for filenames, images in load_images(input_dir, batch_shape):
          adv_images = sess.run(x_adv, feed_dict={x_input: images})
          save_images(adv_images, filenames, output_dir)

if __name__ == '__main__':
  tf.app.run()

**Comment by npapernot** [comment]
The error specifies that your model object is missing an `fprop` method, which probably explains why the code is failing. To see an example of an implementation of a model class, see: https://github.com/tensorflow/cleverhans/blob/f1cf6f06b6f0f68334f7fc5b862b01e439dcdc37/cleverhans/model_zoo/all_convolutional.py#L11

**Comment by xubo0321** [comment]
> The error specifies that your model object is missing an `fprop` method, which probably explains why the code is failing. To see an example of an implementation of a model class, see:
> 
> https://github.com/tensorflow/cleverhans/blob/f1cf6f06b6f0f68334f7fc5b862b01e439dcdc37/cleverhans/model_zoo/all_convolutional.py#L11

Thank you very much，I have solved it.
