### ISSUE TITLE
Cant Use utils_keras.Sequential still thinks its not Cleverhans model

### ISSUE THREAD

**Issue by Jeredriq** [tensorflow/cleverhans#1068]
Hi,

I'm trying to do Saliency Map Method using cleverhans.

My model needs to be keras sequential so for that reason I've searched and found cleverhans.utils_keras, Sequential uses KerasModelWrapper. But for some reason I still get it should be cleverhans model. Here's the stacktrace

> TypeError                                 Traceback (most recent call last)
> <ipython-input-7-2594c5bd6bad> in <module>
>       2 # https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_keras.py
>       3 
> ----> 4 jsma = SaliencyMapMethod(model, sess=sess)
>       5 jsma_params = {'theta': 10.0, 'gamma': 0.15,
>       6                    'clip_min': 0., 'clip_max': 1.,
> 
> c:\users\jeredriq\appdata\local\programs\python\python35\lib\site-packages\cleverhans\attacks\__init__.py in __init__(self, model, sess, dtypestr, **kwargs)
>     911     """
>     912 
> --> 913     super(SaliencyMapMethod, self).__init__(model, sess, dtypestr, **kwargs)
>     914 
>     915     self.feedable_kwargs = ('y_target',)
> 
> c:\users\jeredriq\appdata\local\programs\python\python35\lib\site-packages\cleverhans\attacks\__init__.py in __init__(self, model, sess, dtypestr, **kwargs)
>      55 
>      56     if not isinstance(model, Model):
> ---> 57       raise TypeError("The model argument should be an instance of"
>      58                       " the cleverhans.model.Model class.")
>      59 
> 
> TypeError: The model argument should be an instance of the cleverhans.model.Model class.

And here's my code
```

import numpy as np
from keras import backend
import tensorflow as tf
from keras.callbacks import ModelCheckpoint
from matplotlib import gridspec
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from keras.datasets import mnist
from keras.layers import Dense, Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from cleverhans.attacks import FastGradientMethod
from cleverhans.attacks import BasicIterativeMethod
from cleverhans.attacks import SaliencyMapMethod
from cleverhans.attacks import DeepFool

from cleverhans.utils_keras import Sequential


sess =  backend.get_session()
x = tf.placeholder(tf.float32, shape=(None, 28, 28, 1))
y = tf.placeholder(tf.float32, shape=(None, 10))
# Managing Mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train/=255
X_test/=255
y_train_cat = np_utils.to_categorical(y_train)
y_test_cat = np_utils.to_categorical(y_test)
num_classes = y_test_cat.shape[1]

### Defining Model ###

model = Sequential()      #  <-----  I use Sequential from CleverHans

model.add(Conv2D(32, (5, 5), input_shape=(28,28,1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

history = model.fit(X_train, y_train_cat, epochs=10, batch_size=1024, verbose=1, validation_split=0.7)


### And the problem part ###

jsma = SaliencyMapMethod(model, sess=sess)  # <---- Where I get the exception

jsma_params = {'theta': 10.0, 'gamma': 0.15,
                   'clip_min': 0., 'clip_max': 1.,
                   'y_target': None}

sample_size = 20
one_hot_target = np.zeros((sample_size, 10), dtype=np.float32)
one_hot_target[:, 1] = 1
jsma_params['y_target'] = one_hot_target

X_test_small = X_test[0:sample_size,:]
y_test_small = y_test[0:sample_size]

adv_x = jsma.generate_np(X_test_small, **jsma_params)
```

**Comment by Jeredriq** [comment]
Okay, I still needed to use KerasModelWrapper it seems. I'm not trying to be rude but may I ask why 
 cleverhans.utils_keras exist?

**Comment by npapernot** [comment]
The utils_keras file contains both a Keras defined model and a tool to wrap Keras models into CleverHans models. Does that help?

**Comment by Jeredriq** [comment]
Then it does not really wrap sequential model because I've manually wrapped it 😃

**Comment by npapernot** [comment]
Oh that's because the wrapper can be used for any Keras model and the model that is in the script is just one example of a Keras model, we didn't want to impose a specific model

**Comment by Jeredriq** [comment]
Well, when I import Sequential from cleverhans instead of keras, I expect it to be ready-to-use. But utils_keras is just container for easy usage from cleverhans, i think?

**Comment by npapernot** [comment]
I'm not sure I understand your comment. Are you saying it would make more sense to move the Sequential model from the utils_keras.py script to the tutorial and only keep the KerasModelWrapper in utils_keras.py? Our reasoning for including the model in utils_keras.py was just to give one example of a model. We still wanted to expose in the tutorial how any Keras model can be wrapped into a CleverHans model regardless how it was defined. Is this where your confusion came from? If yes, we could move things around to make it more intuitive.

**Comment by Jeredriq** [comment]
I'm suggesting Sequential and other Keras models should still stay in utils_keras.py but when they're called from utils_keras.py, they should already be wrapped with KerasModelWrapper for easier use because I dont believe anyone would call a keras model from cleverhans' utils_keras.py and use it without wrapping it with KerasModelWrapper.

To put it simply utils_keras should contain this:

`Sequential = KerasModelWrapper(tf.keras.models.Sequential)`


But its just my opinion, you may have your reasons for keeping it the way it is.
