### ISSUE TITLE
adversarial image distorsion

### ISSUE THREAD

**Issue by robomotic** [tensorflow/cleverhans#1069]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see this approach implemented:
https://arxiv.org/pdf/1312.6199.pdf
I believe this is a precursor to the GAN approach?

**Comment by npapernot** [comment]
The L-BFGS approach is implemented here: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks/lbfgs.py
