### ISSUE TITLE
from cleverhans.compat import flags cannot import flags

### ISSUE THREAD

**Issue by AND2797** [tensorflow/cleverhans#1085]
while executing -
`from cleverhans.compat import flags`

i  get the error -
`ImportError: cannot import name 'flags'`

i am using google colab, so not sure if its a colab issue or a cleverhans issue. if everything is fine on your end then i can open an issue with colab. there was a  similar issue earlier, but i am not sure how to fix it for colab. 

i am using,
`!pip install cleverhans` to get the module in colab. 

tf version `1.14.0`

**Comment by npapernot** [comment]
Are you using python3?

**Comment by AND2797** [comment]
Yes, I'm using python3.

**Comment by npapernot** [comment]
Which version of cleverhans are you using?

**Comment by lynn901213** [comment]
uninstall cleverhans, update pip, install the newest cleverhans.
