### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'get_logits'

### ISSUE THREAD

**Issue by bussfromspace** [tensorflow/cleverhans#1089]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

Hi,
I am trying to train a DQN model based on RL-attack examples using this line:
python3 train.py --env Breakout --save-dir ./data/Breakout/ --num-steps 200000000

However, the run fails and gives this error
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    attack=args.attack
  File "/cleverhans/examples/RL-attack/rlattack/deepq/build_graph.py", line 275, in build_train
    act_f = build_act(make_obs_ph, q_func, num_actions, scope=scope, noisy=noisy, reuse=reuse)
  File "/cleverhans/examples/RL-attack/rlattack/deepq/build_graph.py", line 207, in build_act
    q_values = q_values.get_logits(observations_ph.get())
AttributeError: 'Tensor' object has no attribute 'get_logits'

When I check the cleverhans/model.py, get_logits() functions are defined there but the fprop() function return NotImplementedError. I am not sure if that's why I got this error or something related with calling  "from cleverhans.model import CallableModelWrapper" inside build_graph.py file.

I am running this script on Ubuntu16.04, Python3.5, Tensorflow 1.14, CleverHans 3.0.1.

**Comment by npapernot** [comment]
@behzadanksu can you take a look?

**Comment by npapernot** [comment]
cross post from https://stackoverflow.com/questions/57007921/rl-example-attributeerror-tensor-object-has-no-attribute-get-logits

**Comment by behzadanksu** [comment]
This issue was solved in a recent commit of the main repository ( https://github.com/behzadanksu/rl-attack ). I will submit a pull request to Cleverhans in the following days to synchronize the core implementations.

**Comment by npapernot** [comment]
Thanks @behzadanksu !

**Comment by bussfromspace** [comment]
Hi,
Thanks for the response  @npapernot and @behzadanksu. But now I have some further error in the recent commit  [of the rl-attack repository](https://github.com/behzadanksu/rl-attack.) It looks like now I don't have the error I mentioned here, but when I call env.reset(), it gives NotImplementedError.  I tested by just running these two lines and reset works perfectly and I can see the env:
`env = gym.make('Breakout-v0')
obs = env.reset()`

However, when I call this function in train.py file, it gives the error:
`env = gym.make(game_name + "NoFrameskip-v4")
monitored_env = SimpleMonitor(env)
env = wrap_dqn(monitored_env)
obs = env.reset()`
So there must be something wrong with the wrap_dqn function inside atari_wrappers_deprecated.py file. 

I am not sure whether I post this error here or to github page of rl-attack for further discussion.

**Comment by npapernot** [comment]
Could you post this on the github for rl-attack? This looks like it is related to the code implemented there.
