### ISSUE TITLE
ValueError: Dimensions must be equal, but are 512 and 128 for 'sub' (op: 'Sub') with input shapes: [?,512], [?,128]

### ISSUE THREAD

**Issue by ManikandanKurup-Packt** [tensorflow/cleverhans#1091]
After following through all the steps mentioned in readme for "FGSM against FaceNet" I am still getting an error when running facenet_fgsm.py:

Traceback (most recent call last):
  File "facenet_fgsm.py", line 60, in <module>
    model.convert_to_classifier()
  File "facenet_fgsm.py", line 32, in convert_to_classifier
    tf.square(self.embedding_output - self.victim_embedding_input),
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 11574, in sub
    "Sub", x=x, y=y, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2027, in __init__
    control_input_ops)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 512 and 128 for 'sub' (op: 'Sub') with input shapes: [?,512], [?,128].

I changed 128 to 512 in the following line:
self.victim_embedding_input = tf.placeholder(tf.float32,shape=(None, 128))

that led to a new error:
Traceback (most recent call last):
  File "facenet_fgsm.py", line 63, in <module>
    faces1, faces2, labels = set_loader.load_testset(1000)
  File "C:\Users\test\cleverhans\facenet\set_loader.py", line 16, in load_testset
    paths, labels = lfw.get_paths(testset_path, pairs, file_extension)
TypeError: get_paths() takes 2 positional arguments but 3 were given

I tried using a different model, different tensorflow version (1.13.1), but still no progress.

i was able to align the LFW dataset and also run the test using validate_on_lfw.py (even that took me 2 days to figure out.) i am pretty new to this and not quite sure where i went wrong. Any help would be much appreciated.

**To Reproduce**
Follow all the steps mentioned at:
https://github.com/tensorflow/cleverhans/tree/master/examples/facenet_adversarial_faces

**Expected behavior**
I expect it to run as it ideally should 
**Screenshots**
![image](https://user-images.githubusercontent.com/48318375/61627850-7046a900-ac9e-11e9-85c9-980e7aaf1571.png)

**System configuration**
 - OS: Windows 10 x64
 - Python version: 3.7.3
 - TensorFlow version:1.14.0

**Comment by npapernot** [comment]
My guess is that the `lfw` library has been updated since this example was written. Perhaps @BrunoLopezGarcia can confirm?

**Comment by BrunoLopezGarcia** [comment]
I think the file_extension parameter is no longer needed for calling lfw.get_paths, as you can see in this Facenet commit: https://github.com/davidsandberg/facenet/commit/4b98361edf086838169663cd4f85e0b3d24a9475#diff-e19fc7f0584f1545f1ab2059705d2573

**Comment by npapernot** [comment]
@ManikandanKurup-Packt can you let us know if that solved your issue?

**Comment by ManikandanKurup-Packt** [comment]
Sorry for the delayed reply.
I didn't get the solution (maybe cause i'm new to this), but from which file should i remove the file_extension parameter ? 
As far as i checked, there are no file_extension parameter mentioned anywhere that i could find.

**Comment by BrunoLopezGarcia** [comment]
I think you should change this line:

`  paths, labels = lfw.get_paths(testset_path, pairs, file_extension)
`

for this line: 

`  paths, labels = lfw.get_paths(testset_path, pairs)
`

and delete this one:

`file_extension = 'png'
`

in the file set_loader.py

**Comment by ManikandanKurup-Packt** [comment]
I tried what you said but it doesn't seem to make any difference.

![Untitled](https://user-images.githubusercontent.com/48318375/62272300-69672580-b458-11e9-88f5-66fb590fe3fa.png)

**Comment by BrunoLopezGarcia** [comment]
I guess you also have to change 512 to 128 as you did the first time:

`self.victim_embedding_input = tf.placeholder(tf.float32,shape=(None, 128))
`

**Comment by ManikandanKurup-Packt** [comment]
Apparently it is already on 128. I guess i forgot to change it back to 512. 

I tried changing it to 512, but doesn't make a difference.

**Comment by BrunoLopezGarcia** [comment]
I made a few changes in the code and now it works with newer Facenet models. It is still a pull request but you can take a look here: https://github.com/tensorflow/cleverhans/pull/1096

It also exports the generated images now.

**Comment by ManikandanKurup-Packt** [comment]
Finally the code is running without any errors. Thanks to you guys @BrunoLopezGarcia and @npapernot 

Just FYI, the only thing i changed in facenet_fgsm.py is self.layer_names.append('probs') to self.layer_names.append('logits')
Included the code in the set_loader.py file and it worked like a charm. Not sure why though.

![Cap1](https://user-images.githubusercontent.com/48318375/62368063-17ea9380-b549-11e9-8dca-4027f7168bf1.PNG)

**Comment by npapernot** [comment]
If the fix can be useful to others, please consider making a PR to update the current example. thank you!

**Comment by BrunoLopezGarcia** [comment]
@npapernot The fix was already coded in the pull request that I did before.

**Comment by npapernot** [comment]
Excellent thanks!
