### ISSUE TITLE
AttributeError: 'HParams' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by mirza03** [tensorflow/cleverhans#1092]
**Describe the bug**
I'm trying to run multi_GPU Adversarial Training using 'multigpu_advtrain' on cifar10 dataset. I'm getting this error during initialization of the training process.

"AttributeError: 'HParams' object has no attribute __dict__ " in trainer.py line 120

**To Reproduce**
run following command to reproduce:
python3 run_multigpu.py --attack_type_train MadryEtAl_y_multigpu --attack_type_test FGSM,MadryEtAl_y --ngpu 2 --save_dir /home/user/exp/log_dir/advtrain/cifar10_advtrain --nb_epochs 10 --model_type resnet_tf --attack_nb_iter_train 7 --adv_train --dataset cifar10 --eval_iters 5

**System configuration**
 - OS: Ubuntu 18.04 LTS
 - Python3 version: 3.6.8
 - TensorFlow version: 1.13.4

**Using AMD GPUs (RX 470)

Kindly tell me how to overcome this problem. I need some urgent help. Thank You

**Comment by npapernot** [comment]
I'm not sure this code was tested using python3. Have you tried running using python2? Feel free to reopen if that doesn't fix the issue.
