### ISSUE TITLE
Some val images of NIPS 2017 Adversarial Competition download failed

### ISSUE THREAD

**Issue by lin2020** [tensorflow/cleverhans#1093]
I try to download the dev dataset for NIPS 2017 Adversarial Competition. However, some images download failed.

I run "python download_images.py --input_file=dev_dataset.csv --output_dir=./images/"
and get output as follow:

Downloaded 171 imagesDownload failed: 00c3cd597f1ee96f
Download failed: 3692f6967c632fee
Downloaded 178 imagesDownload failed: fa2a7d600b62174e
Downloaded 179 imagesDownload failed: 137ab6ca314e9e35
Downloaded 182 imagesDownload failed: 3dc0e8f854bdc9b3
Download failed: a5949b0719d3ea77
Downloaded 184 imagesDownload failed: 938ada2f2bfa2b68
Downloaded 186 imagesDownload failed: 4bb12984b41d0834
Downloaded 196 imagesDownload failed: 362e4ac62cf888f4
Downloaded 198 imagesDownload failed: 1b57d7bbd673c771
Downloaded 202 imagesDownload failed: 8f9c1e4fd9f4cb2e
Downloaded 209 imagesDownload failed: 871c99d5658c3189
Download failed: 05817a675e7506d1
Downloaded 300 imagesDownload failed: 8f07c92f0af97807
Downloaded 304 imagesDownload failed: e19a59ad09d18497
Downloaded 306 imagesDownload failed: 37e7dc99bf2704c7
Downloaded 397 imagesDownload failed: 7c249a944594a62e
Downloaded 404 imagesDownload failed: d12aad0d18252b40
Downloaded 406 imagesDownload failed: 0f9d8c86a9f38020
Downloaded 408 imagesDownload failed: e3c3f8889ac99aec
Downloaded 422 imagesDownload failed: 55b85f4336d9603a
Downloaded 425 imagesDownload failed: a90d9627e2145090
Downloaded 436 imagesDownload failed: c755f3b0f89028fc
Downloaded 439 imagesDownload failed: 8af30e5c3fa48a08
Downloaded 446 imagesDownload failed: 70db5a1689f89129
Downloaded 448 imagesDownload failed: 6bff4ecb94f1f84e
Downloaded 523 imagesDownload failed: 9a49001b63903f72
Downloaded 524 imagesDownload failed: de40907c1e2c5515
Downloaded 555 imagesDownload failed: 444109f3ccfacc7b
Downloaded 565 imagesDownload failed: 1a94dc47fdd84a95
Downloaded 571 imagesDownload failed: cbcb7444cc827812
Downloaded 576 imagesDownload failed: b9310b9080c06e4f
Download failed: c3cf76709c87255b
Downloaded 592 imagesDownload failed: 5bf502c4a4b7d04d
Downloaded 610 imagesDownload failed: 58420b727fcab02b
Downloaded 639 imagesDownload failed: d2cc2eabfc7bf54a
Downloaded 640 imagesDownload failed: bd3617fcc985fe31
Downloaded 642 imagesDownload failed: c9ddfb1043177de8
Downloaded 644 imagesDownload failed: bba5c56cc3eb07c9
Downloaded 673 imagesDownload failed: 000b7d55b6184b08
Downloaded 688 imagesDownload failed: 8859efd46fab37ff
Download failed: 6b27728f0f816dc6
Downloaded 763 imagesDownload failed: 740981d161a38bad
Download failed: 5b85f98e0105d135
Downloaded 767 imagesDownload failed: 8c5b5bc0f39e2e06
Downloaded 771 imagesDownload failed: 9d5ef11ec55123e5
Downloaded 784 imagesDownload failed: 82179b1d313e0e23
Downloaded 803 imagesDownload failed: 611f453c4bb616b9
Downloaded 814 imagesDownload failed: c663670c06c06ea4
Downloaded 853 imagesDownload failed: 01244097ca8ffdfa
Downloaded 866 imagesDownload failed: 02eb799d147d5f91
Downloaded 989 imagesDownload failed: 5792d4a42d2a82c8
Downloaded 990 imagesDownload failed: 4146a745f9b2f3cb
Downloaded 991 imagesDownload failed: 49c27b439d39a00c
Downloaded 992 imagesDownload failed: 0e71473957df4793
Downloaded 993 imagesDownload failed: 422d08407aeed1be
Download failed: 17f3b8a057bc01be
Downloaded 995 imagesDownload failed: 99f175132cd1c6e2
Downloaded 996 imagesDownload failed: 408bae58c26a8076
Download failed: a414ccf5c51454e0
Downloaded 998 imagesDownload failed: 134bfd93a04b88b2
Downloaded 999 imagesDownload failed: 0aebe24fc257286e
Downloaded 1000 imagesDownload failed: 4053a6a3d0e63c01

**Comment by AlexeyKurakin** [comment]
These images failed to download because they no longer exist.
If you look at dev_dataset.csv and final_dataset.csv, each image id maps to some URL of image on Flickr. If image is gone from Flickr download will fail.

Kaggle packaged dev dataset and put into their website, so you can try to download entire archive from there: https://www.kaggle.com/google-brain/nips-2017-adversarial-learning-development-set

Other than that we can not do anything about failed downloads.
