### ISSUE TITLE
TreeGan 

### ISSUE THREAD

**Issue by robomotic** [tensorflow/cleverhans#1099]
Hello there,
I have read this interesting [paper](https://arxiv.org/abs/1808.07582).
TreeGAN: Syntax-Aware Sequence Generation with Generative Adversarial Networks
 However I am unable to find the source code, it seems a lot of work is required to implement.
Should I try to reach the authors?

**Comment by npapernot** [comment]
This library is about adversarial examples (not generative adversarial networks) so I will close this issue for now.

**Comment by research-guy** [comment]
@robomotic - Did you ever find the source code? I also came along this paper and would like to take a look at the source if it is available

**Comment by robomotic** [comment]
I am sorry no never found it.
