### ISSUE TITLE
GAN resources for mixed continuous and discrete features

### ISSUE THREAD

**Issue by robomotic** [tensorflow/cleverhans#1100]
Hello there,
are there any research papers dealing with generators where the feature space is composed of categorical and continuous features?
I am dealing with executable binaries that have a mix of features for example you will have an entropy float value (bounded), an integer count  of operations (unbounded) and a set of boolean features for the absence or presence of certain function calls.
I was thinking maybe I can discretise the count or float values but I don't know if this is the right approach.

**Comment by npapernot** [comment]
This library is about adversarial examples (not generative adversarial networks) so I will close this issue for now.
