### ISSUE TITLE
Checkpointable error for FGSM attack using cleverhans

### ISSUE THREAD

**Issue by maithal** [tensorflow/cleverhans#1107]
I am trying to attack on an image using cleverhans package and following is my code:

wrap = KerasModelWrapper(model)
fgsm = FastGradientMethod(wrap, sess=sess)
fgsm_params = {'eps': 0.3,
               'clip_min': 0.,
               'clip_max': 1.}
adv_x = fgsm.generate_np(x_validation, **fgsm_params)

for adv_x = fgsm.generate_np(x_validation, **fgsm_params) line I am getting error as 
"Checkpointable._track_checkpointable() passed type <class 'keras.engine.input_layer.InputLayer'>, not a Checkpointable."

What can be the reason?

**Comment by npapernot** [comment]
This looks like a problem with your model definition but it's hard to tell from the limited information you shared. Feel free to reopen if you are still facing this issue, but please add context to your question (e.g., code needed to reproduce the issue)
