### ISSUE TITLE
NotFoundError: libtensorflow_framework.so

### ISSUE THREAD

**Issue by Fansgithub2019** [tensorflow/cleverhans#1109]
**Describe the bug**
Run python generate_imperceptible_adv.py in /examples/adversarial_asr
The following error occurred

 File "/home/fan/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

**To Reproduce**

1. export LINGVO_DEVICE="gpu"
2. export LINGVO_DIR=$HOME/lingvo
3. sudo docker run --rm $(test "$LINGVO_DEVICE" = "gpu" && echo "--runtime=nvidia") -it -v ${LINGVO_DIR}:/tmp/lingvo -v ~/lingvo_compiled:/tmp/lingvo_compiled -v ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro -p 6006:6006 -p 8888:8888 --name lingvo tensorflow:lingvo bash
root@cff77d7949d3:/tmp/lingvo# bazel build -c opt --config=cuda //lingvo:trainer
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository rule 'subpar' returned: {"remote": "https://github.com/google/subpar", "commit": "07ff5feb7c7b113eea593eb6ec50b51099cf0261", "shallow_since": "2018-04-26", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "subpar"}
INFO: Analysed target //lingvo:trainer (35 packages loaded).
INFO: Found 1 target...
Target //lingvo:trainer up-to-date:
  bazel-bin/lingvo/trainer 
INFO: Elapsed time: 74.182s, Critical Path: 22.75s
INFO: 22 processes: 22 processwrapper-sandbox.
INFO: Build completed successfully, 35 total actions
root@cff77d7949d3:/tmp/lingvo# cp -rfL bazel-bin/lingvo/trainer.runfiles/__main__/lingvo /tmp/lingvo_compiled
root@cff77d7949d3:/tmp/lingvo# exit
4.sudo chown -R $USER ~/lingvo_compiled
5.export PYTHONPATH=$PYTHONPATH:~/lingvo_compiled
6.python generate_imperceptible_adv.py
7.see the error

**Expected behavior**
generate imperceptible adversarial examples

**Screenshots**
  
![微信图片_20190917095659](https://user-images.githubusercontent.com/48169187/65005170-8769e600-d931-11e9-9994-82c8ba56dde7.png)

**System configuration**
 - ubuntu16.04
 - Python 3.7
 -  tensorflow-gpu 1.14.0 cuda10 cudnn7

Looking forward to your reply.

**Comment by npapernot** [comment]
This looks like a TF installation problem. Feel free to reopen if that's not the case.
