### ISSUE TITLE
Blackbox model

### ISSUE THREAD

**Issue by maithal** [tensorflow/cleverhans#1124]
Hello Everyone,

I had a small doubt regarding blackbox model using the cleverhans toolbox. according to the code in the tutorial, the basic oracle used is tensorflow based covnet model. Does the cleverhans blackbox model accept keras tensorflow based covnet model as its oracle?

How can be develop confusion matrix for the given tutorial?

Thanks & Best,
M. Aithal

**Comment by npapernot** [comment]
You can use a Keras model if you wrap it as a CleverHans model. Here's an example class to do that: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_keras.py#L97
