### ISSUE TITLE
The documentation page shows nothing.

### ISSUE THREAD

**Issue by YunusBulut** [tensorflow/cleverhans#1126]
In the readme file, it says that the list of attacks can be found on the documentation page: cleverhans.readthedocs.io. However, when I click on that, it shows nothing under the attacks module and model module pages. Here's the screenshot: 
<img width="1435" alt="Screen Shot 2019-10-17 at 10 19 21" src="https://user-images.githubusercontent.com/22097819/66991136-c3769f00-f0c7-11e9-95eb-a47892dc8748.png">

**Comment by npapernot** [comment]
Thanks for letting us know. Do you find the read the docs website useful? It is merely reproducing inline code so I was wondering whether we should just remove it
