### ISSUE TITLE
Madry Pretrained Model dosen't work: cleverhans/examples/madry_lab_challenges/cifar10/

### ISSUE THREAD

**Issue by badchild0912** [tensorflow/cleverhans#1130]
I load the pre-trained model from https://github.com/MadryLab/cifar10_challenge, and set up the environment as ReadMe.md. But  cleverhans/examples/madry_lab_challenges/cifar10/attack_model.py cannot run.

It says: 
Caused by op u'ResNet/input/init_conv/DW/read'
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value ResNet/input/init_conv/DW 

**To Reproduce**
To run the attack on CIFAR-10(cleverhans/examples/madry_lab_challenges/)
1. Clone the CIFAR-10 challenge repository from:
https://github.com/MadryLab/cifar10_challenge
2. Obtain some weights for the Madry Lab model, following the readme
from their project (either download their presupplied weights or train
your own).
3. Set your CIFAR10_CHALLENGE_DIR environment variable to point to 
repository from step 1. 
4. Run
`python cifar10/attack_model.py`
5. See error:
Caused by op u'ResNet/input/init_conv/DW/read'
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value ResNet/input/init_conv/DW 

**Expected behavior**
It should run and give attack examples.

**System configuration**
 - OS: linux
 - Python version: 2.7
 - TensorFlow version: 1.8.0

**Comment by badchild0912** [comment]
Hi,

I found the main problem is the scope name is not matching. For instance, the network demands 'ResNet/input/init_conv/DW/read' while the pre-trained model has '/input/init_conv/DW/read'. It is not matched. But I still have a question about how to match the name. Could you help me with it?

Thank you in advance!

**Comment by zhenxianglance** [comment]
Hi, I couldn't run the code either. I guess its something related to fprop? Any suggestions about how to fix it? Thanks a lot!

**Comment by zhangdong1992** [comment]
I couldn't run the code either.

**Comment by npapernot** [comment]
Unfortunately, we are unable to support the code in the examples folder as stated in the documentation. Feel free to submit a PR if you were able to fix the issue.
