### ISSUE TITLE
 Which attacks have support for multi label in multiclass problem? 

### ISSUE THREAD

**Issue by Shashikant255** [tensorflow/cleverhans#1132]
Can any one please tell me which attacks have the support for multi-label in multi-class problem? @npapernot 
You can see in below images for reference:-
![Capture](https://user-images.githubusercontent.com/42666078/68947135-c0f88980-07da-11ea-94ce-4338cea8b8db.PNG)

**Comment by npapernot** [comment]
I am not sure exactly what you mean by multi-label/multi-class problem but my guess is that you will want an attack that allows you to customize the loss which describes the adversary's goal. Perhaps the PGD attack? 

See https://github.com/tensorflow/cleverhans/pull/1120
