### ISSUE TITLE
Adv should be in eps neighbourhood of Clean Image

### ISSUE THREAD

**Issue by saswatpp** [tensorflow/cleverhans#1135]
According to paper(section 2.2 Basic Iterative Method) :https://arxiv.org/pdf/1607.02533.pdf , 
the Adv example must always lie in the Eps-neighbourhood of the original Clean Image. But the implementation(I saw the pytorch one) in projected_gradient_method for nth iteration clips only the eta and applies it to (n-1)th adv and no steps are taken to ensure the adv example lied in the eps neighbourhood of clean image. Did I misunderstand or is it a wrong implementation ?

**Comment by michaelshiyu** [comment]
For the PyTorch version of ```projected_gradient_descent```, I think the "projection" step is taken care of either in ```clip_eta``` or inside ```fast_gradient_method``` (in the ```optimize_linear``` method, to be specific).

These methods all make sure that the ```eta``` we are adding to ```x``` has some norm (specified by the user) less than or equal to ```eps```, which is the same as saying that the perturbed example is within the ```eps``` neighborhood of the original.

Thanks.

**Comment by saswatpp** [comment]
Thank you for your clarification @michaelshiyu

**Comment by michaelshiyu** [comment]
No problem @saswatpp
