### ISSUE TITLE
Any adversarial attack that sustains after resize attack

### ISSUE THREAD

**Issue by BalaMallikarjuna-G** [tensorflow/cleverhans#1136]
Hi,

This is Bala. I have a query regarding adversarial attack.

Is there any adversarial attack that sustains/consists of added noise, after resize attack ? (adversarial image -> converting into High / low resolution image -> resize to original adverarial image size)

Thanks,
Bala

**Comment by npapernot** [comment]
Most attacks do not take into account post-processing of the image (e.g., the fact that you will downsize the image) but you can introduce what is a larger perturbation to ensure that it will be preserved by the distortion or you can restrict the feature search space to ensure that the perturbations you find are conserved by the distortion.
