### ISSUE TITLE
get gradient when ord=2 in fgm

### ISSUE THREAD

**Issue by JH-Xie** [tensorflow/cleverhans#1139]
in line 231 of [cleverhans/attacks/fast_gradient_method.py](https://github.com/tensorflow/cleverhans/blob/5c1ccc259fa836d69e9582372b0d7f97140a66ef/cleverhans/attacks/fast_gradient_method.py)
`  
elif ord == 2:
    square = tf.maximum(avoid_zero_div,reduce_sum(tf.square(grad),reduction_indices=red_ind,keepdims=True))
    optimal_perturbation = grad / tf.sqrt(square)
`  

I'm wondering why use reduce_sum ranther than reduce_mean in there, shouldn't there describe the disturbation for every pixel?

>

**Comment by npapernot** [comment]
This line is trying to compute the l2_norm (see https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm), which is why there is a sum rather than an average within the square root operation.
