### ISSUE TITLE
Stuck during adversarial training

### ISSUE THREAD

**Issue by erickxhd** [tensorflow/cleverhans#1143]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
A clear and concise description of what the bug is: when using adversarial training (keras) with attack (pgd, cw, deepfool...), program stuck at the begining of runing 'model.fit()' function.
Am I doing something wrong?

**To Reproduce**
1. Go to 'mnist_trtorial_keras.py'
2. Change attack method (line 89) to 'cw' 
line 89: fgsm = CarliniWagnerL2(wrap, sess=sess)
line 90: fgsm_params =  {"clip_min":0., "clip_max": 1.,
                           'batch_size':128, 'confidence':0, 'learning_rate':0.01,
                           'binary_search_steps': 1, 'max_iterations':10, 'abort_early':True,
                           'initial_const':10}
3. Run 'mnist_trtorial_keras.py'
4. Terminal output stuck after show: 
Train on 60000 samples, validate on 10000 samples
Epoch 1/1

**Expected behavior**
This code can not continue for the 'model.fit' function, stuck with 0% CPU and GPU occupancy.

**Screenshots**

python mnist_tutorial_keras.py
C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as 
(type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as 
(type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
  " call new features." % (cur_dir, ch_dir))
2020-01-23 15:46:08.119592: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-01-23 15:46:08.527948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2020-01-23 15:46:08.548932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-01-23 15:46:09.677521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-23 15:46:09.682937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-01-23 15:46:09.710805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-01-23 15:46:09.714766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6387 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Defined Keras model.
c:\users\xieha\cleverhans\cleverhans\attacks_tf.py:27: UserWarning: attacks_tf is deprecated and will be removed on 2019-07-18 or after. Code should import functions from their new locations directly.
  warnings.warn("attacks_tf is deprecated and will be removed on 2019-07-18"
c:\users\xieha\cleverhans\cleverhans\compat.py:22: UserWarning: <function reduce_max at 0x0000019744942950> is deprecated. Switch to calling the equivalent function in tensorflow.  This function was originally needed as a compatibility layer for old versions of tensorflow,  but support for those versions has now been dropped.
  warnings.warn(str(f) + " is deprecated. Switch to calling the equivalent function in tensorflow. "
c:\users\xieha\cleverhans\cleverhans\compat.py:22: UserWarning: <function reduce_sum at 0x0000019744942158> is deprecated. Switch to calling the equivalent function in tensorflow.  This function was originally needed as a compatibility layer for old versions of tensorflow,  but support for those versions has now been dropped.
  warnings.warn(str(f) + " is deprecated. Switch to calling the equivalent function in tensorflow. "
Train on 60000 samples, validate on 10000 samples
Epoch 1/1

Info from Task manager:
Name       CPU          MEM       GPU
Python        0%      1.367.7MB   0%

**System configuration**
 - Win10
 - Python version: 3.6.5
 - TensorFlow version: 1.12 (I also try TF 1.9,1.13,1.14,1.15 and outcome same problem).

**Comment by npapernot** [comment]
Are you using the last version of CleverHans?

________________________________

**Comment by carlini** [comment]
It might help to put some debug statements and see where the code hangs.

**Comment by npapernot** [comment]
Feel free to reopen with detailed debug statements, will close for now
