### ISSUE TITLE
After i install cleverhans by pip, i can't import any function from it

### ISSUE THREAD

**Issue by Nyn2019** [tensorflow/cleverhans#1147]
The way that i install cleverhans: pip install cleverhans
The version of python: 3.7.2
The version of cleverhans: 3.0.1

Problem: 
from cleverhans.compat import reduce_max
error: Unresolved reference reduce_max
There are many such problems， what should i do??

**Comment by michaelshiyu** [comment]
Hi @Nyn2019, the CleverHans on PyPI is pretty old. Please clone from Github and install from your local clone. Something like

```
git clone https://github.com/tensorflow/cleverhans.git
cd cleverhans
pip install .
```

Thanks.

**Comment by Nyn2019** [comment]
> Hi @Nyn2019, the CleverHans on PyPI is pretty old. Please clone from Github and install from your local clone. Something like
> 
> ```
> git clone https://github.com/tensorflow/cleverhans.git
> cd cleverhans
> pip install .
> ```
> 
> Thanks.

Thanks a lot 🙂

**Comment by michaelshiyu** [comment]
@Nyn2019 no problem! Please close the issue if you think it's been resolved. Thanks :)
