### ISSUE TITLE
Implement JSMA symbolically 

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#116]
Improve JSMA implementation so we can feed it more than one input at a time

**Comment by IvanKush** [comment]
do you mean multithreading, etc?

**Comment by npapernot** [comment]
Sorry the title of this is somewhat unrelated to the description now that I changed it. The goal was to implement the JSMA completely symbolically in TF (no Python/Numpy involved). This requires among other things to change the current Python while loop into a TF while loop.

**Comment by ajing** [comment]
Sorry for my limited knowledge about Tensorflow. For the part like:

```
        search_domain = set([i for i in xrange(nb_features)
                             if adv_x[0, i] < clip_max])
```

Could this also be written symbolically?

**Comment by npapernot** [comment]
It should be possible to rewrite this symbolically yes. I contacted @gongzhitao who implemented a version of this here: https://github.com/gongzhitaao/tensorflow-adversarial/blob/master/attacks/jsma.py#L102

There should be a PR to work on this soon.

**Comment by gongzhitaao** [comment]
In the `test_attacks.py`, where is the `sess.run(tf.global_variables_initializer())`?

**Comment by npapernot** [comment]
For instance here: https://github.com/tensorflow/cleverhans/blob/master/tests_tf/test_attacks.py#L461
