### ISSUE TITLE
How to save and load model?

### ISSUE THREAD

**Issue by shenqixiaojiang** [tensorflow/cleverhans#139]
Hello,I have trouble in loading model when I saved the model with TF format. The model can't load using 'saver.restore'. 
So could you give me some suggestion on saving and loading the trained model?
Thanks.

**Comment by npapernot** [comment]
This is an issue that we have to address yes. The save feature doesn't work because we are defining the model using keras. Any contributions are welcome if you are able to make it work, otherwise I would suggest defining the model directly using tf

**Comment by goodfeli** [comment]
Quick comment: I think the bug where reloading the model in Keras doesn't work might be due to an "initialize_all_variables" call. That's worth checking at some point.

**Comment by shenqixiaojiang** [comment]
I have tried some methods for addressing it. Unfortunately,it didn't work. 
Finally, FGSM is implemented by Keras with TF backend.

**Comment by shenqixiaojiang** [comment]
@npapernot @goodfeli 
I had tried some methods to address it. Unfortunately,it didn't work.
Finally, FGSM was implemented by Keras with TF backend.
During this, I found a funny thing that same architectures in different platform had different performance and the difference was huge which was explored in the MNIST datasets. The phenomenon seems to be inconsistent with "The Space of Transferable Adversarial Examples".

**Comment by npapernot** [comment]
@shenqixiaojiang, did you get a chance to look at what @goodfeli suggested?

**Comment by shenqixiaojiang** [comment]
@npapernot Sorry,I made a mistake of the suggestion of @goodfeli .  Now, it works. 
Thank you very much.

**Comment by npapernot** [comment]
Would you be willing to open a PR to include the code that is able to load/save models?

**Comment by shenqixiaojiang** [comment]
@npapernot  yeah,I'll be will to. A PR is opened for this problem.
