### ISSUE TITLE
Remove all test_mnist_tutorial_*.py

### ISSUE THREAD

**Issue by carlini** [tensorflow/cleverhans#167]
These tests are really slow to run, flakey, and should be replaced by unit tests of each individual method.

**Comment by goodfeli** [comment]
I think they should be sped up, rather than removed. They're the only thing we have resembling an integration test. Integration tests are important as well as unit tests.

**Comment by goodfeli** [comment]
Also, before we had the tests, people routinely made edits to the tutorials themselves that broke the tutorials.

**Comment by npapernot** [comment]
Given that #155 cut testing time to about 12mn, I'm going to close this for now. Once unit test have a better coverage of the code base, we can decrease the test time even more by further reducing the problem size of tutorial tests.
