### ISSUE TITLE
pip install works only as root or single user

### ISSUE THREAD

**Issue by cbienpourtoi** [tensorflow/cleverhans#178]
Usually, when I install a module with pip as root, all users can access it. Installing cleverhans with 
`pip install -e git+http://github.com/tensorflow/cleverhans.git#egg=cleverhans
`
works as root, but as another user, I get :
```
In [1]: import cleverhans
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-754f8ba0e85b> in <module>()
----> 1 import cleverhans

ModuleNotFoundError: No module named 'cleverhans'
```
I can install it specifically for a user (pip --user), but this is not what I want. Is it on my side that there is something wrong, or is there a problem in the bundle rights management on your side?

**Comment by npapernot** [comment]
If you want to install for a particular user, you can use `pip --user` as you pointed out. 

Alternatively, you could also clone the repository and append a path to it in the `PYTHONPATH` variable. 

Feel free to re-open if this does not solve your problem.
