### ISSUE TITLE
change spacing to 4 spaces in pure tf tutorial

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#179]
all other code has 2 spaces

**Comment by goodfeli** [comment]
I think we should standardize on 2 spaces for consistency with TensorFlow, especially now that this repository lives in the TensorFlow organization.

**Comment by carlini** [comment]
I don't have a strong opinion, but PEP8 says python should have 4 spaces (and all non-google python code I'm aware of uses 4). Do you see any benefits of going to 2 spaces?

**Comment by goodfeli** [comment]
actually I'm confused by @npapernot 's earlier comment; it looks like most of CleverHans has 4 spaces

**Comment by npapernot** [comment]
My bad. This was a mistake, I meant to say that most of the code base has 4 spaces, but the tutorial has 2 spaces. 

I don't have a preference towards 2 or 4 spaces and am happy to use either.
