### ISSUE TITLE
[README] wget: dependency not listed.

### ISSUE THREAD

**Issue by omtcyfz** [tensorflow/cleverhans#186]
download_dataset.sh uses `wget` through

https://github.com/tensorflow/cleverhansblob/master/examples/nips17_adversarial_competition/sample_attacks/download_checkpoints.sh
```bash
wget http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz
```

and https://github.com/tensorflow/cleverhans/blob/master/examples/nips17_adversarial_competition/sample_defenses/download_checkpoints.sh (similar)

However, wget is not installed on Unix by default (e.g. I use curl and didn't have wget up until now) and thus I think it's reasonable to list it in the README dependencies section, especially because when I was running the script for the first time the output was really verbose and I couldn't notice the `wget: command not found` error.

**Comment by goodfeli** [comment]
Done.
