### ISSUE TITLE
error in mnist_tutorial_jsma.py

### ISSUE THREAD

**Issue by kirk86** [tensorflow/cleverhans#189]
There is the following error when one defines a different number of classes as and argument.
```
Attacking input 1/10
Traceback (most recent call last):
  File "mnist_tutorial_jsma.py", line 226, in <module>
    app.run()
  File "/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "mnist_tutorial_jsma.py", line 215, in main
    learning_rate=FLAGS.learning_rate)
  File "mnist_tutorial_jsma.py", line 141, in mnist_tutorial_jsma
    target_classes = other_classes(nb_classes, current_class)
    other_classes_list.remove(class_ind)
ValueError: list.remove(x): x not in list
```

**Comment by npapernot** [comment]
It looks from the error that you are trying to use a class index `class_ind` that is too large (i.e., larger than `nb_classes`). Otherwise, could you give us a bit more context so we can understand what went wrong?

**Comment by kirk86** [comment]
@npapernot yeah sure, apologies, my bad. So what I did is I just run the tutorial example without changing anything. The only thing that I changed is the user defined argument `nb_classes`. The default value is set to 10 I just used 5 in this case.

**Comment by npapernot** [comment]
If you only changed the `nb_classes` to 5, it is normal to get this error because some of the inputs have labels between 5 and 9 (in `Y_test`).

If you want to reduce `nb_classes` to 5, you should also filter the data so it only includes examples from classes `0` to `4` included.
