### ISSUE TITLE
DecompressionBombWarning and corrupt exif data on images download

### ISSUE THREAD

**Issue by rshpeley** [tensorflow/cleverhans#211]
On downloading the images I got this warning for image 486,

> Downloaded 486 images/home/shpeley/miniconda3/lib/python3.6/site-packages/PIL/Image.py:2438: DecompressionBombWarning: Image size (102638475 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning)

and also this warning,

> Downloaded 989 images/home/shpeley/miniconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:709: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 10. 
  warnings.warn(str(msg))

Yet when I check the files with `ls dataset/images -l` there's no apparent file size issues. 

Using `ls dataset/images | wc -l` shows a count of 1000 files, so no files are missing.

Removing the `images` directory and reinstalling gave the same errors. I'm using python 3.6.1 and pillow 4.2.1

**Comment by npapernot** [comment]
I suppose this is related to the adversarial competition? If yes, @AlexeyKurakin might have the answer to your problem

**Comment by rshpeley** [comment]
Yes. These are the images installed through the download_data.sh script in the examples/nips17_adversarial_competition/ folder.

**Comment by rshpeley** [comment]
Looking at dev_dataset.csv, image 486 has this data.

> ImageId	URL	x1	y1	x2	y2	TrueLabel	TargetClass	OriginalLandingURL
ad43e858c614db4d	https://c1.staticflickr.com/9/8263/28394550932_d93637d26b_o.jpg	0.0	0.25	0.5625	1.0	968	71	https://flickr.com/7831824@N04/28394550932

This is the photo cropped and scaled from the images folder.
![ad43e858c614db4d](https://user-images.githubusercontent.com/18505950/28491372-5c1b8ee0-6ead-11e7-93b7-ebc05aba6533.png)

If that's how the cropping and rotation were intended, the image came out fine -- definitely nothing which would blow up the number of pixels for a DOS attack. Perhaps this error is new in pillow 4.2.1?

**Comment by rshpeley** [comment]
As a separate issue, if that's not the cropping and rotation you're looking for then the `download_image()` function in `download_images.py` needs to read the exif rotational data and rotate the image if needed before applying crop and resize.

**Comment by AlexeyKurakin** [comment]
@rshpeley That's exactly how image 486 should look like after cropping and resizing.

I haven't seen DecompressionBombWarning, but I used rather old version of Pillow (2.3.0), so this message was probably added in newer version.
I think the reason why you see the warning is because this image is high resolution (2736 × 3648) and cause pillow to complain about it. But it looks like image was correctly downloaded, cropped and resized.

Regarding corrupt EXIF data. download_image script does not use EXIF data, so it should not cause the problem either.
