### ISSUE TITLE
stop_gradient(pred) when model prediction is used to attack

### ISSUE THREAD

**Issue by fartashf** [tensorflow/cleverhans#242]
When the model's prediction is used instead of true labels, it makes more sense to do `stop_gradient(pred)`.

This can be fixed by doing `stop_gradient` after these lines:
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks.py#L391
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks.py#L208
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks_tf.py#L54

**Comment by goodfeli** [comment]
We can definitely wrap argmax ops in stop_gradients to keep the TensorFlow graph smaller while still computing the same value. If the predictions are used in something other than an argmax, then `stop_gradient` actually changes the derivatives. Depending on the application, we may or may not want to consider the model fixed.

**Comment by npapernot** [comment]
The three lines that Fartash pointed out would add a `stop_gradient` after an argmax, so it seems like an optimization worth making a PR for.

**Comment by goodfeli** [comment]
OK, thanks
