### ISSUE TITLE
FGSM Training Question

### ISSUE THREAD

**Issue by malcolmregan** [tensorflow/cleverhans#250]
This is more of a stack exchange style (seeking expert help) question rather than a report of a technical issue. But I thought I'd try my luck here, as you guys are the experts:

My issue is that a model being trained on FGSM examples does not learn anything. I'm fairly certain the cause of this issue lies in the details of my implementation as it differs slightly from the implementation used in the Cleverhans tutorials (see end of post), but am having trouble seeing why or how any of the details of my implementation would make any difference to the training process.

The problem is best demonstrated by comparing the output of the training function when a model is being trained on the MNIST training set and the output of the training function when a model is being trained on FGSM examples derived from the MNIST training set (I'm using keras 'fit' function rather than the functions shipped with the cleverhans package):

```
Training model on MNIST:
	Epoch 1/10
	60000/60000 [==============================] - 51s - loss: 1.1707 - acc: 0.6933      
	Epoch 2/10
	60000/60000 [==============================] - 51s - loss: 0.3488 - acc: 0.8959     
	Epoch 3/10
	60000/60000 [==============================] - 51s - loss: 0.2744 - acc: 0.9192     
	Epoch 4/10
	60000/60000 [==============================] - 51s - loss: 0.2286 - acc: 0.9324     
	Epoch 5/10
	60000/60000 [==============================] - 51s - loss: 0.1948 - acc: 0.9419     
	Epoch 6/10
	60000/60000 [==============================] - 51s - loss: 0.1697 - acc: 0.9498     
	Epoch 7/10
	60000/60000 [==============================] - 51s - loss: 0.1507 - acc: 0.9547     
	Epoch 8/10
	60000/60000 [==============================] - 51s - loss: 0.1364 - acc: 0.9599     
	Epoch 9/10
	60000/60000 [==============================] - 51s - loss: 0.1240 - acc: 0.9632     
	Epoch 10/10
	60000/60000 [==============================] - 52s - loss: 0.1154 - acc: 0.9655     
	acc on MNIST test set: 0.9675
```
```
Training model on ~60000 FGSM examples derived from MNIST training set:
	Epoch 1/10
	57811/57811 [==============================] - 47s - loss: 116.9297 - acc: 0.0992     
	Epoch 2/10
	57811/57811 [==============================] - 47s - loss: 116.9235 - acc: 0.0649     
	Epoch 3/10
	57811/57811 [==============================] - 47s - loss: 116.9233 - acc: 0.0639     
	Epoch 4/10
	57811/57811 [==============================] - 47s - loss: 116.9232 - acc: 0.0634     
	Epoch 5/10
	57811/57811 [==============================] - 47s - loss: 116.9232 - acc: 0.0633     
	Epoch 6/10
	57811/57811 [==============================] - 47s - loss: 116.9232 - acc: 0.0635     
	Epoch 7/10
	57811/57811 [==============================] - 47s - loss: 116.9231 - acc: 0.0631     
	Epoch 8/10
	57811/57811 [==============================] - 47s - loss: 116.9231 - acc: 0.0625     
	Epoch 9/10
	57811/57811 [==============================] - 47s - loss: 116.9231 - acc: 0.0616     
	Epoch 10/10
	57811/57811 [==============================] - 47s - loss: 116.9231 - acc: 0.0623     
```
I do not understand why this would happen as the FGSM examples are clearly recognizable as digits, just with added adversarial noise. Any ideas why training would not be successful on the FGSM examples? 

Some details of my implementation that may be important to problem solution:
- I am using the Keras 'fit' function instead of the model_train() and model_eval() functions used in the Cleverhans tutorials

- To allow the use of the keras 'fit' function, I compile the cnn_model after initialization with 
 ```  
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
```

- Instead of passing the FGSM example generator to a trainer function symbolically, as done in Cleverhans tutorials, I save the FGSM examples as numpy files, and then train the model on a dataset comprised of these saved examples.

Thank you,
Malcolm

**Comment by goodfeli** [comment]
It should be possible to train the model on FGSM examples (that's what our tutorial does) so there is presumably a bug in your code. You could try to synchronize it with our Keras tutorial to find where your code deviates from ours.

**Comment by malcolmregan** [comment]
Thank you response. I figured it out shortly after I posted: I was storing the targets of the FGSM examples as integers when in fact they were one-hot vectors. Probably should have been the first place I looked.
Thank you!
