### ISSUE TITLE
Better seeding / test that seeding works

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#253]
Our tutorial tests still show significant differences when run multiple times. See the comments on this PR for some examples: https://github.com/tensorflow/cleverhans/pull/249

We should figure out which part of the tutorials is not seeded correctly, seed it, and add a test that running the tutorial twice gives nearly the same result.

**Comment by goodfeli** [comment]
I did some work toward this but didn't complete it, in this PR: https://github.com/tensorflow/cleverhans/pull/255

The PR adds the necessary tests, but with loose tolerance. This will hopefully make sure we at least don't add more non-deterministic ops, but I haven't found the cause of the current non-determinism yet.

**Comment by goodfeli** [comment]
@npapernot  and I discussed this today during the hackathon. Our current state of knowledge is: TensorFlow isn't deterministic so we won't be able to make CleverHans completely deterministic. There are still some things we could do to make CleverHans more deterministic, like set eigen to be single threaded.

**Comment by catherio** [comment]
@goodfeli Can you clarify what work still has to be done now that #308 has been merged?

**Comment by npapernot** [comment]
David would be the person to talk to about this :) My understanding is that there is little chance we will get this solved without making changes to tensorflow

**Comment by goodfeli** [comment]
Which David?

I think the main thing to do is to run the determinism tests with Eigen configured to be single-threaded. I'm not sure whether there are more sources of non-determinism in TensorFlow besides that.

CleverHans will probably always be non-deterministic during real use because the underlying linear algebra primitives are non-deterministic, but we can write unit tests that check that CleverHans isn't adding new non-determinism by failing to seed RNGs.

**Comment by npapernot** [comment]
This would be @david-berthelot :)

David can confirm, but that's exactly what he found out too I believe

**Comment by david-berthelot** [comment]
I have narrowed the problem down to a trivially small test case. The problem was consecutive calls to tf.Session() seemed to have their internal seed (it's been 2 weeks I looked at it, didn't have time since then so I'm not entirely clear).
