### ISSUE TITLE
support for pytorch multiprocessing dataloader

### ISSUE THREAD

**Issue by lfz** [tensorflow/cleverhans#257]
Hi, the pytorch docker requires the `--ipc=host` flag in the cmd

https://github.com/pytorch/pytorch#docker-image

An example is `nvidia-docker run --rm -ti --ipc=host pytorch/pytorch:latest`

could you add this in the framework?

**Comment by npapernot** [comment]
I assume this is related to the NIPS competition?

**Comment by lfz** [comment]
yes, shouldn't I post this issue here?

**Comment by goodfeli** [comment]
Yes, @npapernot is just clarifying which part of the codebase this issue is about. @AlexeyKurakin , can you take on this issue?

**Comment by goodfeli** [comment]
We think this doesn't matter now that the competition is over. Also, we think competitors were able to use pytorch using their own custom containers.
