### ISSUE TITLE
Kaggle user reports a bug in FGSM when using uint8 images

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#265]
https://www.kaggle.com/c/nips-2017-non-targeted-adversarial-attack/discussion/39626#222159

**Comment by npapernot** [comment]
Based on the Kaggle discussion, it seems that the error is due to converting the images back from floats to uint8 after having ran the attack; rather than during the attack itself (which is computed on floating point values). Correct me if I'm wrong.
