### ISSUE TITLE
pyfunc issues a weird error on cpu on a windows machine : help needed

### ISSUE THREAD

**Issue by avsanjay** [tensorflow/cleverhans#280]
error in this function    
        def cw_wrap(x_val, y_val):
            return np.array(attack.attack(x_val, y_val), dtype=np.float32)
        wrap = tf.py_func(cw_wrap, [x, labels], tf.float32)

py_func not returning tensor 
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'NoneType' object has no attribute 'run'
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0, one_hot)]]

**Comment by npapernot** [comment]
Did you check that you are giving a valid session to the Attacks class?

**Comment by avsanjay** [comment]
yes that was the issue. a valid session resolves it. thank you.
