### ISSUE TITLE
check model load / save functions

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#281]
remove FLAGS from `utils_tf.py`

**Comment by yenchenlin** [comment]
Hello @npapernot ,

It seems that now the only FLAGS in `utils_tf.py` exists in function `tf_model_load`, and this function is only called in `mnist_tutorial_cw.py`.

I deleted the FLAGS in function `tf_model_load` and confirmed that `mnist_tutorial_cw.py` still works fine. Does it mean we can simply add a deprecated message in function `tf_model_load` for FLAGS and completely delete FLAGS from `utils_tf.py` in the near future?

**Comment by npapernot** [comment]
Yes, we could deprecate the logic of this if statement https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_tf.py#L276 and require that the `file_path` argument be supplied.

**Comment by catherio** [comment]
@npapernot Is this issue resolved now that #303 has been merged?

**Comment by npapernot** [comment]
I don't think this is resolved completely, I believe Aurko is working on it though.

**Comment by catherio** [comment]
@royaurko Any updates?
