### ISSUE TITLE
How to get the genereated adversarial exmaples ?

### ISSUE THREAD

**Issue by georgiazhang** [tensorflow/cleverhans#311]
Hi, I'm new to the Cleverhans, recently I just study my first program mnist_tutrial_tf.py.
But I still get no idea about the specific phases of generation and attacking.
Can anyone tell me how can I get the adversarial examples (the images) which can help me understand the process more clearly?
Thank you very much!

**Comment by goodfeli** [comment]
Hi Georgia,

Which of the following do you need help with?

- How to get TensorFlow tensors representing adversarial examples
- How to get NumPy ndarrays containing specific adversarial examples
- How to view an ndarray as an image on your monitor
- How to save an ndarray as an image file

-Ian
