### ISSUE TITLE
Targeted FGSM

### ISSUE THREAD

**Issue by malcolmregan** [tensorflow/cleverhans#312]
Has targeted FGSM been shown to reliably work?

**Comment by goodfeli** [comment]
Do you have a minimal example of it failing?

For people working on CH, maybe regard this issue as "Verify that targeted FGSM has adequate tests and if not add them"

**Comment by david-berthelot** [comment]
There's already a unit test example for targeted FGSM:
https://github.com/tensorflow/cleverhans/blob/master/tests_tf/test_attacks.py#L158

Feel free to reopen if you can provide a reusable test case.

**Comment by malcolmregan** [comment]
Thank you for the test, I will look at that. 

Attached is a simple case demonstrating targeted FGSM failure. An MNIST model is trained similarly to  Cleverhans tutorials and then targeted FGSM is performed on examples.

The script prints the target that FGSM is trying to achieve and the class of the corresponding example. These two things rarely match. 

The attached script runs from the cleverhans directory.

[FGSMTargetFailureExample.zip](https://github.com/tensorflow/cleverhans/files/1463115/FGSMTargetFailureExample.zip)

**Comment by goodfeli** [comment]
Can I ask you two debugging questions before we look into it ourselves?

1) Does untargeted FGSM work? If not, then maybe there's a problem with the way your model is integrated into CleverHans.

2) Does targeted BasicIterativeMethod with several iterations work? If so, then maybe your model is robust enough to resist FGSM.

**Comment by npapernot** [comment]
@malcolmregan did you get a chance to take a look again?

**Comment by goodfeli** [comment]
Without more concrete evidence that this is a bug, I'm going to assume this just means targeted FGSM is not a very strong targeted algorithm against this model. Feel free to reopen if you find more concrete evidence that this is a software bug.
