### ISSUE TITLE
model.Model is not an abstract class

### ISSUE THREAD

**Issue by gokul-uf** [tensorflow/cleverhans#315]
More of a nit-pick here,
model.Model has `__metaclass__ = ABCMeta` so I'm assuming that it's to be extended before use.

However, I installed `cleverhans` via `pip` and I am able to initiate an instance of `Model`.

This shows that the property is not implemented properly. I'm not sure what's the best way to do this,
but decorating the method we want to overload with `@abstractmethod` (cf. https://dbader.org/blog/abstract-base-classes-in-python) 

I'd be happy to send a PR with the changes if that's the desired behaviour.

Additionally, it would be good to mention which methods we want users to implement when extending in the docs.

**Comment by npapernot** [comment]
Yes, it would be great to have a PR to address these issues, you may want to send a quick email describing the changes you'll make to `cleverhans-dev@googlegroups.com`, I just accepted your membership request

**Comment by gokul-uf** [comment]
Great, I'll write it up. I'm new to cleverhans, so could you let me know which methods *must* be overloaded? Looks like `get_layer_names` and `fprop` are the only candidates.

**Comment by gokul-uf** [comment]
Closing after discussions on cleverhans-dev
