### ISSUE TITLE
Best practices for data preprocessing prior to adversarial image generation?

### ISSUE THREAD

**Issue by sgfin** [tensorflow/cleverhans#316]
When building neural nets based on ImageNet networks (e.g. ResNet) via transfer learning, my understanding is that best practice is to use apply the same preprocessing function that was employed during the training of the original networks. In Keras, for example, the preprocessing function is available as `keras.applications.resnet50.preprocess_input,` which can be called on new images prior to training/testing the fine-tuned network.

However, the preprocessing function significantly changes the appearance of the images, and we want our adversarial examples to represent small changes to _real_ images, not small changes to _preprocessed_ images.  As such, I'm curious about what is considered the standard practice for handling preprocessing in adversarial examples for ImageNet models.  Potential options I could see are:

- Run standard preprocessing as in `keras.applications.resnet50.preprocess_input` prior to inputting into the NN and cleverhans, generate corresponding adversarial examples, and then apply a "de-processing" function that reverses the preprocessing function to view the adversarial examples.
- Don't apply preprocessing at all
- Apply some modified form of preprocessing that is easier to reverse

Any tips?

**Comment by cihangxie** [comment]
Normally we will use the first option. After "de-processing", that is the adversarial example you want. You can refer to the load_images() & save_images() at  cleverhans/examples/nips17_adversarial_competition/sample_attacks/fgsm/attack_fgsm.py
 
For the second option, neural network will not recognize the image correctly, thus the whole process is invalid.

**Comment by sgfin** [comment]
Thanks so much for the reply.  I had some mixed results implementing the "de-processing" step -- which is what had led me to ask this question in the first place -- but I think I may have finally debugged it.  For the benefit of any future passer-bys, the issue was that naive "de-processing" code (as implemented in the example shown above) will run into numerical issues if the original images are scaled at 256 (as in jpegs).

To demonstrate this, consider the following function, which simulates running the standard imagenet pre-processing code and then trying to "de-process" it by directly performing complementary math operations:

```
def depreprocess(y, finalMult = True):
    x /= 255.
    x *= 2.
    x -= 1.
    x += 1.
    x /= 2.
    if finalMult:
        x *= 255.
    return x
```

I'll run it on the same image (once as a png, once as a jpg) with and without the "finalMult" flag.  In the case of png, it only works if you _do_ apply the final multiplication.  In the case of jpg, it only works if you _don't._ This makes sense from a numerical standpoint, but could screw people over if they reuse simple code.

Run on a png:

![image](https://user-images.githubusercontent.com/2760120/33195910-bd0711bc-d0a9-11e7-8812-25688d4e39a4.png)

Run on a jpg:

![image](https://user-images.githubusercontent.com/2760120/33195925-db4fea54-d0a9-11e7-8b98-1e1746a9de5f.png)

**Comment by cihangxie** [comment]
I guess one error in your deproc() function is that you should add mean values (since you minus mean values in the pre-processing). 

You can look the pre-process code: https://github.com/keras-team/keras/blob/master/keras/applications/imagenet_utils.py#L2, and try to **inverse** this procedure for your deproc() function. Two important variables you should notice are: data_format (channel first or channel last) and  mode.

**Comment by recluse27** [comment]
Thanks a lot! 
There is a problem still. The input image is de-processing correctly but it's an opposite situation with adversarial image.

Take a look, please
https://github.com/recluse27/diplo/blob/master/deprocessing.ipynb

**Comment by cihangxie** [comment]
fgsm_params = {'eps': 0.3, 'clip_min': 0., 'clip_max': 1.} are not valid for you, since your input range are not within [0,1]. You should figure out the right values for clip_min and clip_max. Or since you are using fgsm, which is a single-step attack, you can first set clip_min to a very small value (e.g., -1000) and clip_max to a very large value (e.g., 1000); after you get your adv image, you can then clip the deprocessed image to [0,255]
