### ISSUE TITLE
Unable to run the attacks and defenses?

### ISSUE THREAD

**Issue by rittikaadhikari** [tensorflow/cleverhans#317]
![image](https://user-images.githubusercontent.com/13933251/33177200-cb2ab282-d02f-11e7-8402-90d60b60091f.png)

Whenever I try to run the run_attacks_and_defenses.py or the run_attacks_and_defenses.sh, I end up getting stuck at "Restoring parameters from inception_v3.ckpt" -- would anyone know how I can get past this point?

Thanks

**Comment by goodfeli** [comment]
@AlexeyKurakin ?

**Comment by AlexeyKurakin** [comment]
Could you provide some additional information about the issue.

1) Did you modify the code of the attack? I yes - does it work fine with unmodified version?

2) How long did you wait? It looks like you running it on CPU, and it's quite slow to run inception model on CPU. So it might be the case that your model is just running and you need to wait longer.
Restoring parameters from the checkpoint may take up to a few minutes (depeding on you CPU and disk speed). After parameters are restored model starts generating adversarial examples, which may take some time on CPU
To see if your model actually doing anything, you can check output folder to see if there is any files saved there. Also you can add additional printing/logging before and after session run.

**Comment by npapernot** [comment]
Thanks Alex, feel free to reopen the issue @rittikaadhikari if that did not solve it for you.
