### ISSUE TITLE
Error in jacobian_augmentation in attacks_tf

### ISSUE THREAD

**Issue by KristinLieber** [tensorflow/cleverhans#321]
I think line 456 shouldn't have the "2*".  It looks like it is writing over every other x value in a stacked file of 2 copies of x values.  That means it is keeping two copies of every other x.  Also, the success rate on adversarial examples goes up when you increase the epochs, which is counter-intuitive. 

I made this change and the code is running the way it should.  The oracle has a harder time correctly identifying adversarial examples when you increase the number of augmentations to the substitute training set.

**Comment by goodfeli** [comment]
Thank you for reporting this! Great catch
