### ISSUE TITLE
"Tensor name not found" in Example attacks

### ISSUE THREAD

**Issue by huntergregal** [tensorflow/cleverhans#335]
Trying to run the target class example using the inception_v3.ckpt checkpoint
(cleverhans/examples/nips17_adversarial_competition/sample_targeted_attacks/iter_target_class/) but getting this error:

```
NotFoundError (see above for traceback): Tensor name "InceptionV3/AuxLogits/Conv2d_2a_3x5/BatchNorm/beta" not found in checkpoint files inception_v3.ckpt
	 [[Node: save/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_4/tensor_names, save/RestoreV2_4/shape_and_slices)]]
```

Am also receiving this same error when trying other attacks as well

**Comment by catherio** [comment]
@npapernot This has been sitting for a little while, are you up to take a look or triage/delegate?

**Comment by npapernot** [comment]
@AlexeyKurakin would be the best to deal with this issue, he merged most of the code and checkpoints for the adversarial competition.  From the error, it looks like the checkpoint and model definition don't match.

**Comment by cihangxie** [comment]
@huntergregal I guess the error is that you are using the images with smaller size for the attack (i.e., your image size is smaller than 299x299).

Your variable name is InceptionV3/AuxLogits/Conv2d_2a_3x5, while the default name stored at checkpoint is InceptionV3/AuxLogits/Conv2d_2a_5x5. You can take a look at 
https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v3.py/#L510, where the kernel size is generated by kernel_size = _reduced_kernel_size_for_small_input(aux_logits, [5, 5]), which is determined by the input size.

If this is the problem, i think there are two ways to solve it: (a) resize your image to 299x299; or (2) comments all line related to auxlogits in your model definition.

**Comment by goodfeli** [comment]
@huntergregal I'm assuming @cihangxie 's fix works for you. If not feel free to reopen the issue
