### ISSUE TITLE
Convert .py tutorial files into Jupyter notebooks.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/cleverhans#348]
Would there be any interest in having the cleverhans .py files converted into Jupyter notebooks? 

It would assist with readability (HTML-exports and friendly formatting on GitHub!), and also give an opportunity to add annotations and illustrations rather than in-line comments.

**Comment by npapernot** [comment]
I would prefer to keep the files as .py so new users have less overhead to
run the tutorials, but I'm open to having new tutorials in notebooks

**Comment by npapernot** [comment]
I'm closing this for now as this is not an issue, but feel free to email `cleverhans-dev@googlegroups.com` if you're looking to put together a notebook. Thanks!
