### ISSUE TITLE
The model argument should be an instance of the cleverhans.model.Model class.

### ISSUE THREAD

**Issue by blgnksy** [tensorflow/cleverhans#349]
Hi,
When I call the FastGradientMethod an error rises that : "The model argument should be an instance of the cleverhans.model.Model class."

<ipython-input-8-7bdd93be4f06> in <module>()
        5     model = InceptionModel(num_classes)
        6 
----> 7     fgsm  =  FastGradientMethod(model)

What can I do?
Best,
B.A.

**Comment by goodfeli** [comment]
Wrap your InceptionModel class in a cleverhans.model.Model class. Check out the CleverHans tutorials for examples.

**Comment by blgnksy** [comment]
I wrap my InceptionModel with the Model class. But Another error rises that "AttributeError: 'module' object has no attribute 'model'" I read the tutorials. I used the same manner, but unable to solve it.

**Comment by goodfeli** [comment]
We'd need to see your code and a traceback to be able to help with that

**Comment by npapernot** [comment]
This seems to be a problem with the InceptionModel class since ` cleverhans.model.Model` does not have a model attribute

**Comment by blgnksy** [comment]
This is my model class:
```
class InceptionModel(object):
    def __init__(self, num_classes):
        self.num_classes = num_classes
        self.built = False

    def __call__(self, x_input):
        """Constructs model and return probabilities for given input."""
        reuse = True if self.built else None
        with slim.arg_scope(inception.inception_v3_arg_scope()):
            _, end_points = inception.inception_v3(
                            x_input, num_classes=self.num_classes, is_training=False,
                            reuse=reuse)
        self.built = True
        output = end_points['Predictions']
        probs = output.op.inputs[0]
        return probs
```
And the code par t to attack the network:

```
tf.logging.set_verbosity(tf.logging.INFO)

with tf.Graph().as_default():
    x_input = tf.placeholder(tf.float32, shape=batch_shape)

    model = cleverhans.model.Model(InceptionModel(num_classes))

    fgsm  = FastGradientMethod()
    x_adv = fgsm.generate(x_input, eps=eps, clip_min=-1., clip_max=1.)

    saver = tf.train.Saver(slim.get_model_variables())
    session_creator = tf.train.ChiefSessionCreator(
                      scaffold=tf.train.Scaffold(saver=saver),
                      checkpoint_filename_with_path=checkpoint_path,
                      master=tensorflow_master)

    with tf.train.MonitoredSession(session_creator=session_creator) as sess:
        nontargeted_images = sess.run(model, feed_dict={x_input: images})
```

**Comment by goodfeli** [comment]
Can we also see the stack trace?

**Comment by blgnksy** [comment]
> AttributeError                            Traceback (most recent call last)
> <ipython-input-6-f20d89f9976f> in <module>()
>       4     x_input = tf.placeholder(tf.float32, shape=batch_shape)
>       5 
> ----> 6     model = cleverhans.model.Model(InceptionModel(num_classes))
>       7 
>       8     fgsm  = FastGradientMethod(model)
> 
> AttributeError: 'module' object has no attribute 'model'

**Comment by goodfeli** [comment]
Do you know why your trace isn't going inside FastGradientMethod and isn't including line numbers within the file?

**Comment by blgnksy** [comment]
Unfırtunately, I don't know. But I will try to find it.

**Comment by blgnksy** [comment]
Hi,
How should I import the module and use the Model and Attacks classes?  I imported the module the way in tutorials but unable to use the model and attack class. Am I missing something?

I can use attack class but unable to use model class if I import like this:
`from cleverhans.attacks import FastGradientMethod` 

If I use these imports
```
import cleverhans.model
import cleverhans.attacks

models= cleverhans.model.Model(InceptionModel(num_classes))
fgsm  = cleverhans.attacks.FastGradientMethod(models)
x_adv = fgsm.generate(x_input, eps=eps, clip_min=-1., clip_max=1.)
```
Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-7a387e6b5be9> in <module>()
      4     x_input = tf.placeholder(tf.float32, shape=batch_shape)
      5 
----> 6     models= cleverhans.model.Model(InceptionModel(num_classes))
      7     fgsm  = cleverhans.attacks.FastGradientMethod(models)
      8     x_adv = fgsm.generate(x_input, eps=eps, clip_min=-1., clip_max=1.)

TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by npapernot** [comment]
One easier and cleaner way might be to rewrite your inception model class to inherit directly from the CleverHans model class since it's already only a wrapper for the slim model. You can look at the wrapper we included for keras in the utils_keras.py file for some guidance.

**Comment by charmainewu** [comment]
hello ，have you solved the problem ? I have same problem.

**Comment by Abhishek7081** [comment]
from cleverhans.model import Model 
Including this should solve the issue.

**Comment by winnie1009** [comment]
**I rewrote "class InceptionModel"**
**code:**


class InceptionModel(Model):
  """Model class for CleverHans library."""

  def __init__(self, nb_classes):
    super(InceptionModel, self).__init__(nb_classes=nb_classes,
                                         needs_dummy_fprop=True)
    self.built = False

  def __call__(self, x_input, return_logits=False):
    """Constructs model and return probabilities for given input."""
    reuse = True if self.built else None
    with slim.arg_scope(inception.inception_v3_arg_scope()):
      # Inception preprocessing uses [-1, 1]-scaled input.
      x_input = x_input * 2.0 - 1.0
      _, end_points = inception.inception_v3(
          x_input, num_classes=self.nb_classes, is_training=False,
          reuse=reuse)
    self.built = True
    self.logits = end_points['Logits']
    # Strip off the extra reshape op at the output
    self.probs = end_points['Predictions'].op.inputs[0]
    if return_logits:
      return self.logits
    else:
      return self.probs

  def get_logits(self, x_input):
    return self(x_input, return_logits=True)

  def get_probs(self, x_input):
    return self(x_input)


def _top_1_accuracy(logits, labels):
  return tf.reduce_mean(
      tf.cast(tf.nn.in_top_k(logits, labels, 1), tf.float32))
