### ISSUE TITLE
Formatting Issues in cleverhans.readthedocs.io

### ISSUE THREAD

**Issue by gokul-uf** [tensorflow/cleverhans#354]
Small nitpick but the parameter lists in the docs for attacks is off.
For ex, :param eps: is not formatted correctly in most attacks and in `VirtualAdversarialMethod` the entire parameter list is incorrectly formatted.

**Comment by catherio** [comment]
![image](https://user-images.githubusercontent.com/245037/36291049-9d0ac2d0-127d-11e8-9f77-2ea8d3252a41.png)

I think we just need more newlines.
