### ISSUE TITLE
generate_np doesn't support variable dtypes

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#357]
The dtypes of most tensors in the `generate_np` caching system are hard-coded to float32. If you pass in a float64 tensor, nothing sensible happens. This is a restriction compared to the `generate` interface.

I have never been a fan of `generate_np` and would be in favor of just removing it since it's one of the more difficult features to maintain and doesn't add any actual adversarial example functionality.

We may also want to investigate whether eager mode + generate provide the functionality that generate_np is meant to provide.

Finally, if we want to keep generate_np, the interface should probably be changed, so that there are multiple allowed dtypes for each argument and the choice of specific dtype is treated as a structural argument.

**Comment by goodfeli** [comment]
cc @npapernot @carlini

**Comment by npapernot** [comment]
I don't use generate_np much so I don't have a strong opinion either way, but transitioning to eager mode would be a good compromise for the use cases I can think of

**Comment by goodfeli** [comment]
SGTM
