### ISSUE TITLE
A minor bug in tutorial model

### ISSUE THREAD

**Issue by michaelzhou0723** [tensorflow/cleverhans#359]
On line 102 of tutorial_models.py https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/tutorial_models.py

I think it should be output_shape[0] = batch_size

**Comment by npapernot** [comment]
Good catch, this does not seem to affect the code given that input and output shape variables are not used in the ReLU that follows the Conv2D layer. Would you mind looking through the file and making a PR?

**Comment by michaelzhou0723** [comment]
No problem :)

**Comment by npapernot** [comment]
Closed by #360
