### ISSUE TITLE
cannot initialize an attack class with callable function

### ISSUE THREAD

**Issue by michaelzhou0723** [tensorflow/cleverhans#361]
Take `FastGradientMethod` as an example, its `__init__` method checks and wraps any callable function with `CallableModelWrapper`. However it's done after `super(FastGradientMethod, self).__init__(model, back, sess)`, which raises an exception if the model argument is not an instance of `Model` class.

A simple modification would be exchanging their order of execution in every subclass of Attack.

**Comment by catherio** [comment]
Thanks for the PR!
