### ISSUE TITLE
Tiny bug in adversarial patch notebook

### ISSUE THREAD

**Issue by shreyashankar** [tensorflow/cleverhans#376]
In `AdversarialPatch.ipynb`, the function `show_patch` takes one argument, but the API shows it as `show_patch()` and the function `load_patch` calls `show_patch()` incorrectly. Just FYI :-)

**Comment by goodfeli** [comment]
@nottombrown can you take a look?

**Comment by nottombrown** [comment]
Solved by #383 - Thanks @shreyashankar !
