### ISSUE TITLE
A problem about clipping the eta in Basic Iterative Method.

### ISSUE THREAD

**Issue by Lizenan1995** [tensorflow/cleverhans#381]
We will clip the eta in every iteration, but it seems that for ord = 1 or 2, the eta will access the bound eps directly.  In the other word, the l1 (or l2) norm of eta equals to eps after each iteration. 
```         
            # Clipping perturbation eta to self.ord norm ball
            if self.ord == np.inf:
                eta = tf.clip_by_value(eta, -self.eps, self.eps)
            elif self.ord in [1, 2]:
                reduc_ind = list(xrange(1, len(eta.get_shape())))
                if self.ord == 1:
                    norm = tf.reduce_sum(tf.abs(eta),
                                         reduction_indices=reduc_ind,
                                         keep_dims=True)
                elif self.ord == 2:
                    norm = tf.sqrt(tf.reduce_sum(tf.square(eta),
                                                 reduction_indices=reduc_ind,
                                                 keep_dims=True))
                eta = eta * self.eps / norm
```
Maybe we just need clip the eta when it is out of bound,I'm not sure if this is a mistake or I misunderstood the algorithm. Thanks in advance.

**Comment by goodfeli** [comment]
For reference, the code quoted is from here:
https://github.com/tensorflow/cleverhans/blob/a18f3319015cebc4a83dae3b7217019b5654f641/cleverhans/attacks.py#L404

I agree that it looks like a bug, and instead we should call the `clip_eta` function:
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_tf.py#L380

@AlexeyKurakin can you confirm?

**Comment by AlexeyKurakin** [comment]
Yes, this is a bug.
I'll fix it today

**Comment by goodfeli** [comment]
This was fixed by https://github.com/tensorflow/cleverhans/pull/387
