### ISSUE TITLE
Color Images Adverserial distortions

### ISSUE THREAD

**Issue by aashish-kumar** [tensorflow/cleverhans#391]
Hello,
I tried using the attacks to generate adversarial for Color Images but the attacks introduce color artifacts in the Images. Has there been work done toward generating adversarial without significant color artifacts?
Thanks

**Comment by gokul-uf** [comment]
Could you give an example?
I've seen this happen when my epsilon was too large.

**Comment by aashish-kumar** [comment]
I tried JSMA and Carlini Wagner with default settings and FGSM with epsilon 0.3 
Its working fine for grayscale Images but with Color Images the adverserial Noise is too apparent

**Comment by AlexeyKurakin** [comment]
Could you show an example of color artifacts?

Sometimes color artifacts happen when you forget to clip an image values and then tried to save or show it.
For example, by default matplotlib assumes that all pixels of float32 image are in range [0; 1]. If any values are outside of this range then image will have weird color artifacts when shown.
If this is your problem then the solution is to clip values of all channels of all pixels to be in [0, 1] range.

**Comment by aashish-kumar** [comment]
@All The theta for gamma was set to 1.0 for JSMA attack which was resulting in uneven color changes in the adversarial Images. reducing it to 0.1 produced good attacks. Thanks
