### ISSUE TITLE
tf 1.8 support

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#397]
We currently get several deprecation warnings when running tensorflow 1.8. We should update to the point that we get no tf deprecation warnings when running the tutorials and tests. We should also add tf 1.8 to the travis bot.

**Comment by npapernot** [comment]
Closing this given that `mnist_tutorial_tf.py` does not raise any deprecation warnings anymore. If anyone notices another warning, feel free to open an issue.
