### ISSUE TITLE
JSMA MemmoryError

### ISSUE THREAD

**Issue by recluse27** [tensorflow/cleverhans#403]
keras: 2.1.4
tf: 1.5.0
cleverhans: 2.0.0-aa80e13d0f63be3197ba61290f46e44d
Ubuntu: 17.10

`jsma = SaliencyMapMethod(wrap, sess=sess)`

`jsma_params = {'gamma': 0.1, 'clip_min': 0., 'clip_max': 1.}`
`adv_x2 = jsma.generate_np(x_val,**jsma_params)`

`adv_pred2 = np.argmax(model.predict(adv_x2), axis = 1)`
`adv_acc2 =  np.mean(np.equal(adv_pred2, y_val)) `

FGSM and BasicIterativeMethod went okay. 
Error text:

> MemoryError                               Traceback (most recent call last)
<ipython-input-22-82bc83f252e1> in <module>()
      6 jsma_params = {'gamma': 0.1,
      7                'clip_min': 0., 'clip_max': 1.}
----> 8 adv_x2 = jsma.generate_np(x_val,**jsma_params)
      9 
     10 adv_pred2 = np.argmax(model.predict(adv_x2), axis = 1)

> ~/src/cleverhans/cleverhans/attacks.py in generate_np(self, x_val, **kwargs)
    139 
    140         if hash_key not in self.graphs:
--> 141             self.construct_graph(fixed, feedable, x_val, hash_key)
    142 
    143         x, new_kwargs, x_adv = self.graphs[hash_key]

> ~/src/cleverhans/cleverhans/attacks.py in construct_graph(self, fixed, feedable, x_val, hash_key)
    113 
    114         # now we generate the graph that we want
--> 115         x_adv = self.generate(x, **new_kwargs)
    116 
    117         self.graphs[hash_key] = (x, new_kwargs, x_adv)

> ~/src/cleverhans/cleverhans/attacks.py in generate(self, x, **kwargs)
    688                                   theta=self.theta, gamma=self.gamma,
    689                                   clip_min=self.clip_min,
--> 690                                   clip_max=self.clip_max)
    691         else:
    692             from .attacks_tf import jacobian_graph, jsma_batch

> ~/src/cleverhans/cleverhans/attacks_tf.py in jsma_symbolic(x, y_target, model, theta, gamma, clip_min, clip_max)
    431     increase = bool(theta > 0)
    432 
--> 433     tmp = np.ones((nb_features, nb_features), int)
    434     np.fill_diagonal(tmp, 0)
    435     zero_diagonal = tf.constant(tmp, tf.float32)

> /usr/local/lib/python3.6/dist-packages/numpy/core/numeric.py in ones(shape, dtype, order)
    186 
    187     """
--> 188     a = empty(shape, dtype, order)
    189     multiarray.copyto(a, 1, casting='unsafe')
    190     return a

> MemoryError:

**Comment by AngusG** [comment]
What is the shape of `x_val`?

**Comment by recluse27** [comment]
(1, 224, 224, 3)

https://github.com/recluse27/diplo/blob/master/deprocessing.ipynb

**Comment by npapernot** [comment]
It may be the case that you are trying to allocate a numpy array that is too big to fit in your available RAM? Here the JSMA is trying to create an array of size nb_features x nb_features where nb_features = 224 * 224 * 3. Perhaps this prior implementation of the attack might help you: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks_tf.py#L260

**Comment by recluse27** [comment]
I thought 4 GB RAM would be enough.
Don't yo know are there any free cloud resources to try JSMA there? Kaggle doesn't allow to upload keras pretrained models, for example

**Comment by npapernot** [comment]
Could you give more details on how to reproduce the issue?

**Comment by vandeppce** [comment]
`jsma = SaliencyMapMethod(model, sess=sess)
  sess.run(tf.global_variables_initializer())
  x_adv = jsma.generate(x_input, clip_min=-1., clip_max=1.)
`
When I run, I got the following error text:

MemoryErrorTraceback (most recent call last)
/notebooks/AdversarialExamples/test.py in <module>()
     96         sess.close()
     97 
---> 98 main()

/notebooks/AdversarialExamples/test.py in main()
     84         jsma = SaliencyMapMethod(model, sess=sess)
     85         sess.run(tf.global_variables_initializer())
---> 86         x_adv = jsma.generate(x_input, clip_min=-1., clip_max=1.)
     87         saver = tf.train.Saver(slim.get_model_variables())
     88         saver.restore(sess, checkpoint_path)

/usr/local/lib/python3.5/dist-packages/cleverhans/attacks.py in generate(self, x, **kwargs)
    691                                   theta=self.theta, gamma=self.gamma,
    692                                   clip_min=self.clip_min,
--> 693                                   clip_max=self.clip_max)
    694         else:
    695             from .attacks_tf import jacobian_graph, jsma_batch

/usr/local/lib/python3.5/dist-packages/cleverhans/attacks_tf.py in jsma_symbolic(x, y_target, model, theta, gamma, clip_min, clip_max)
    433     increase = bool(theta > 0)
    434 
--> 435     tmp = np.ones((nb_features, nb_features), int)
    436     np.fill_diagonal(tmp, 0)
    437     zero_diagonal = tf.constant(tmp, tf_dtype)

/usr/local/lib/python3.5/dist-packages/numpy/core/numeric.py in ones(shape, dtype, order)
    186 
    187     """
--> 188     a = empty(shape, dtype, order)
    189     multiarray.copyto(a, 1, casting='unsafe')
    190     return a

MemoryError: 

I am not sure whether there are anyone else encounter the same error, I think maybe Numpy does not support a very big matrix, so maybe using Scipy generate sparse matrix can work?

**Comment by npapernot** [comment]
Yes, it may be the case that you do not have enough RAM to create the numpy array in memory. I always ran the code on machines with over 90GB RAMs so I may not have noticed that. How much memory do you have?

**Comment by vandeppce** [comment]
I understand, thank you! I ran it on a Titan Xp GPU with about 12GB Memory, so maybe I can run the code on a server with 90GB RAMs, instead of using GPU.

**Comment by npapernot** [comment]
I think the numpy array would have to be stored in RAM so GPU memory is likely irrelevant here (unless I missed something).

**Comment by npapernot** [comment]
(feel free to reopen if this is not the case)

**Comment by tzaiyang** [comment]
I have same problem too when i use the JSMA, My RAM is 32GB, and GPU memory is 11GB*2, I don't think the problem is out of my memory, How did you deal with it?
