### ISSUE TITLE
When Attack.get_or_guess_labels(), allow y_target to be None

### ISSUE THREAD

**Issue by giuscri** [tensorflow/cleverhans#406]
To my understanding, when you call `FastGradientMethod.generate` you can't pass `y_target=None` as an argument and expect cleverhans to behave like you didn't pass it.

https://github.com/tensorflow/cleverhans/blob/fcf1e2a18e72dd42280f04a50fce3eb4e0b20fcf/cleverhans/attacks.py#L200-L205

Changing check into `'y_target' in kwargs and kwargs['y_target'] is not None` would make the function behave as one would expect.

**Comment by npapernot** [comment]
Thanks for raising the issue, would you be able to put together a PR to address it?
