### ISSUE TITLE
How save image files on tutorial

### ISSUE THREAD

**Issue by Uno-Takashi** [tensorflow/cleverhans#414]
I built cleverhans environment. And, executed mnist_tutorial_tf.py.
The mnist_tutorial_tf.py worked fine. And, I done some easy change like save models.

I want to save the fooling image files generated by FGSM(Such as , The panda image in the "Explaining and Harnessing Adversarial Examples"). But  It is not working well.

What  source code should I add to The tutorial?

**Comment by goodfeli** [comment]
Some of the tutorials show one way of visualizing the adversarial examples: https://github.com/tensorflow/cleverhans/blob/0670677010f3fed21b1ea91c4571c16fff661e0c/cleverhans_tutorials/mnist_tutorial_cw.py#L215

**Comment by jugi92** [comment]
I would like to export the adversarial examples in the MNIST Blackbox Example to my file system:
https://github.com/tensorflow/cleverhans/blob/36e3c78fbcbdcec93718edd1450eedd9131616f0/cleverhans_tutorials/mnist_blackbox.py#L254

I experimented with the following code:
```
def convert_and_save_image(image):
        encoded_image = tf.image.encode_jpeg(image, format="grayscale")
        writeOp = tf.write_file("./example_images/adversarials/" + 
                         datetime.datetime.now().strftime("%Y%m%d%H%M%S")
                         + str(round(random.random() * 1000)) + ".jpg",
                         encoded_image)
        return writeOp

casted_image_tf = tf.cast(x_adv_sub, tf.uint8)
encoded_images_tf = tf.map_fn(convert_and_save_image, casted_image_tf)
session.run(encoded_images_tf)
```
But as writeOp is an operation it can not be run by session.run() and also needs some values for the placeholders. It would be awesome someone could help me with this.

**Comment by jugi92** [comment]
I just appended this code in Line 255 in the MNIST Blackbox Example to get PIL images from the Tensors and store them in the file system:
 ```
encoded_images = sess.run(x_adv_sub, feed_dict={x: X_test})

    import os
    from PIL import Image
    import datetime 
    directory = "/tmp/adv_learn/example_images/adversarials/" + datetime.datetime.now().strftime("%Y%m%d%H%M") + "/"
    if not os.path.exists(directory):
        os.makedirs(directory)
    images = []
    for idx, img_arr in enumerate(encoded_images):
        img = Image.fromarray(np.squeeze(img_arr) * 255) # Pixels are in range 0 to 1 and need to be in 0-255 for PIL
        #img.show()
        path = directory + str(idx) + ".jpeg"
        img.save(path, "JPEG")
        images.append({"Path": path, "img": img})
```
