### ISSUE TITLE
Accuracy for black-box attack

### ISSUE THREAD

**Issue by aashish-kumar** [tensorflow/cleverhans#416]
Using the mnist_blackbox.py script. I get the following result:

Test accuracy of oracle on adversarial examples generated using the substitute: 0.7038578680203046

This accuracy used to be <10 percent. Any one else saw the change? Is this because of the bug fix for #400

**Comment by npapernot** [comment]
I don't think we implemented the fix mentioned by Ian in #400. Could you take a look and make a PR if that solves the issue?

**Comment by npapernot** [comment]
I assume that #421 addresses your issue but feel free to reopen one if it does not.
