### ISSUE TITLE
Clever Hans Imports all broken for me

### ISSUE THREAD

**Issue by carsonsmith87** [tensorflow/cleverhans#419]
Successfully downloaded the entire cleverhans directory using pip on Mac. Now, in mnist_tutorial_keras_tf.py all the 'from cleverhans.[]  import' statements are erring with "This inspection detects names that should resolve but don't.

Any advice to fix this would be awesome, thank you.

**Comment by goodfeli** [comment]
I see you closed the issue, did you fix it?
