### ISSUE TITLE
Attack Docs Missing

### ISSUE THREAD

**Issue by ysharma1126** [tensorflow/cleverhans#425]
http://cleverhans.readthedocs.io/en/latest/source/attacks.html

What happened? Please restore.

**Comment by ysharma1126** [comment]
Any response?

**Comment by goodfeli** [comment]
@nottombrown Do you know what happened?

**Comment by nottombrown** [comment]
Odd. I'll take a look and see if I can track down the issue

**Comment by npapernot** [comment]
Thanks for the PR @nottombrown 

Do we have to trigger something to rebuild the docs? They don't seem to have refreshed yet despite the PR being merged

**Comment by nottombrown** [comment]
There was a second configuration issue with the hosted docs.

Resolved now and the docs will auto-rebuild whenever there is a push to `master`.

http://cleverhans.readthedocs.io/en/latest/source/attacks.html
