### ISSUE TITLE
Can anyone clarify the use of sign(gradient) as np.inf norm?

### ISSUE THREAD

**Issue by jrounds** [tensorflow/cleverhans#429]
Quick question; though perhaps this is the wrong place.

When I just step back and think about the infinity norm of a gradient, I think of it as max of the absolute value of the gradient.  

But in cleverhans infinity normalization on the gradient is treated as it as the sign operator on the gradient: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks_tf.py#L74

I was wondering if anyone could give me a quick hint on what to read to understand the justification?

**Comment by goodfeli** [comment]
You're right that for a vector v, the infinity norm is abs(v).max().

When we use the sign function, we are not computing the infinity norm. We are computing a vector that obeys a constraint on the infinity norm.

Specifically,

max_v dot(v, g) subject to max_norm(v) <= eps
= eps * np.sign(g)
