### ISSUE TITLE
Create consistent attack parameter naming scheme

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/cleverhans#436]
Move away from adopting the naming scheme (arbitrarily) chosen by authors, and establish names with consistent semantics across attacks.

Proposed naming scheme:
  - "eps": the maximum perturbation applied to a clean data sample
  - "step_count": the number of steps to take in an iterative attack
  - "step_size": the size of step to take at each iteration
  - "true_label": (disjoint w/ target_label) the true one_hot label to move away from
  - "target_label": (disjoint w/ true_label) the target one_hot label to move towards
  - "clip_max": clip final adversarial example to this maximum value
  - "clip_min": clip final adversarial example to this minimum value

**Comment by goodfeli** [comment]
+1

**Comment by goodfeli** [comment]
When we do this, we need to remember to respect the 6 month deprecation warning rule

**Comment by goodfeli** [comment]
Do you have any suggestions for building this into the structure of the code (e.g. so you get the argument names via inheritance) or for making a tool that automatically flags probable violations?

**Comment by npapernot** [comment]
I agree with the proposed argument names but would recommend running this by the cleverhans-dev mailing list in case someone else has an objection
