### ISSUE TITLE
PyTorch in setup.py

### ISSUE THREAD

**Issue by aashish-kumar** [tensorflow/cleverhans#452]
I think the torch tutorial requires pytorch but it is not part of setup.py.

**Comment by goodfeli** [comment]
@npapernot or @nottombrown do you want to comment on this? I see you wrote the lines of setup.py involving TensorFlow. I don't know as much about how setup.py works or what the "explicit dependence" issue is, if we have a policy of requiring all option dependencies or if we can install different versions with different dependencies, etc.

**Comment by npapernot** [comment]
I would prefer not making pytorch a mandatory dependency, which would add some overhead for those using tensorflow only. I'm not familiar with the explicit dependence issue either, but @nottombrown should be able to comment. 

One suggestion I had would be to (1) add pytorch as an extra dependency and (2) change the Travis matrix to include a pytorch config and (3) remove pytorch from other configs of the matrix (to have tensorflow only configs)

**Comment by nottombrown** [comment]
I‘m on the road and can’t see the offending code currently, but papernot’s
suggestion seems reasonable to me. Pytorch should be an “extras” dependency
