### ISSUE TITLE
How to get NumPy ndarrays containing specific adversarial examples?

### ISSUE THREAD

**Issue by chenhx1992** [tensorflow/cleverhans#454]
Hi, 

I am new to cleverhans. I have tried generate function and generate_np function on my own model. The generate function work well but the generate_np has some error. 

Thus, I would like to ask, is there any other way to get NumPy ndarrays containing specific adversarial examples without generate_np?

Hope get your answer soon, thanks in advance!

**Comment by npapernot** [comment]
You can also run the tensor returned by `generate` in a session by providing a `feed_dict` manually

**Comment by npapernot** [comment]
Feel free to reopen with a more specific description of the error if that does not solve your issue
