### ISSUE TITLE
Undefined name 'self' in madry_cifar10_model.py

### ISSUE THREAD

**Issue by cclauss** [tensorflow/cleverhans#455]
flake8 testing of https://github.com/tensorflow/cleverhans on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./examples/madry_lab_challenges/cifar10/madry_cifar10_model.py:267:31: F821 undefined name 'self'
    return tf.nn.xw_plus_b(x, self.w, self.b)
                              ^
./examples/madry_lab_challenges/cifar10/madry_cifar10_model.py:267:39: F821 undefined name 'self'
    return tf.nn.xw_plus_b(x, self.w, self.b)
                                      ^
2       F821 undefined name 'self'
2
```

**Comment by goodfeli** [comment]
@david-berthelot could this be related to the recent changes to `Model`?

**Comment by david-berthelot** [comment]
Yes I think so, looks like set_input_shape is not called. I can look into it.

**Comment by david-berthelot** [comment]
Looked at it, it's working from the latest master as far as  can tell.

**Comment by cclauss** [comment]
Are you sure that line 267 is getting executed?

**Comment by david-berthelot** [comment]
I am not familiar with that example, I checked if some recent refactoring broke it, but running it I see no problem, it runs properly (using the latest master branch). Did you try running:
`python cifar10/attack_model.py`
