### ISSUE TITLE
FaceNet Dimensions must be equal error

### ISSUE THREAD

**Issue by jchaykow** [tensorflow/cleverhans#460]
I'm receiving an error running [FGSM](https://github.com/tensorflow/cleverhans/tree/master/examples/facenet_adversarial_faces) with the latest model download from FaceNet. 

Now I am pretty sure I have narrowed down the error cause to this line:

```
    distance = tf.reduce_sum(
                tf.square(self.embedding_output - self.victim_embedding_input),
                axis=1)
```

And I believe the issue is that `victim_embedding_input` is defined with shape `(None, 128)` and somewhere else `embedding_output` is defined as 512.

```
    self.victim_embedding_input = tf.placeholder(
                tf.float32,
                shape=(None, 128))
and

    graph = tf.get_default_graph()
            self.face_input = graph.get_tensor_by_name("input:0")
            self.embedding_output = graph.get_tensor_by_name("embeddings:0")
```

This is the part I can't figure out. Is `graph.get_tensor_by_name("embeddings:0")` just a 512 size tensor already when the model is loaded in from Facenet? If so, how can the FGSM operate with the 128 sizing without receiving this error:

```
    ~/tensorflow/python/framework/ops.py", line 1589, in _create_c_op
        c_op = c_api.TF_FinishOperation(op_desc)

    tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 512 and 128 for 'Sub' (op: 'Sub') with input shapes: [?,512], [?,128].
    
    Traceback (most recent call last):
      File "facenet_fgsm.py", line 60, in <module>
        model.convert_to_classifier()
      File "facenet_fgsm.py", line 32, in convert_to_classifier
        tf.square(tf.subtract(self.embedding_output, self.victim_embedding_input))
    
    File "~/tensorflow/python/ops/math_ops.py", line 223, in subtract
        return gen_math_ops.sub(x, y, name)
```

**Comment by npapernot** [comment]
@BrunoLopezGarcia  could you take a look? I think this is an example you wrote.

**Comment by BrunoLopezGarcia** [comment]
Seems like the Facenet model you are using works with embedding vectors of size 512. In order to fix the error you can change the size of the placeholder to 512:

`    self.victim_embedding_input = tf.placeholder(
                tf.float32,
                shape=(None, 512))`

Maybe we could write this step in the "How to run" part of the README.md.

**Comment by BrunoLopezGarcia** [comment]
I don't think it will take a much larger memory requirement.

**Comment by ChengruiMeng** [comment]
yes, i met this problem too. I suggest you update the code version in the sample.
