### ISSUE TITLE
Adversarial Patch question about the patch training

### ISSUE THREAD

**Issue by KSSchmidt** [tensorflow/cleverhans#467]
Hello,
I am fairly new to Tensorflow and Github as well and hope this is the right place to ask content-related questions regarding the adversarial patch example.

After reading the [paper](https://arxiv.org/abs/1712.09665) by T.Brown et al, I got interested in adversarial patches for my thesis.
I am currently using the code of the adversarial patch notebook to generate different shapes/patterns of robust patches to see how effective changes to the initial circular shape are.

How exactly are the currently saved patch and the patch variable (used in the var_list of the GradientDescentOptimizer in _make_mode_and_ops) connected?
And how is the patch trained in regard to the transformation applied on the training batch? For example when the patch is applied to the bottom left corner of an image with a 12° rotation and scaling to 0.1 of the original size, how does the gradient of the patched input image translate to the patch in general?

Thank you in advance for your time!

**Comment by nottombrown** [comment]
Hey, we use a differentiable spatial transformation that allows the gradient to flow back into the correct part of the patch image. You can see it in the tensorflow operations that apply the rotations and translations.
