### ISSUE TITLE
SPSA attack is not tested by Travis

### ISSUE THREAD

**Issue by nottombrown** [tensorflow/cleverhans#495]
SPSA has some nice tests:
https://github.com/tensorflow/cleverhans/blob/2ebda1ddab0cc3084316b0db7516c8b8e2cc796a/examples/test_imagenet_attacks.py

However, since they live in the `examples` directory, rather than in `cleverhans` or `tests_tf`, they don't get executed by the [travis.yml manifest](https://github.com/tensorflow/cleverhans/blob/master/.travis.yml#L77)

Is this intentional @juesato ?

**Comment by nottombrown** [comment]
Looking a bit more deeply, it seems like it's not there because it is too expensive to run on Inception on a travis CPU. Could we perhaps test it on MNIST or a toy dataset?

**Comment by goodfeli** [comment]
I would vote to test it on a small subset of MNIST (e.g. one small minibatch).

**Comment by nottombrown** [comment]
Yeah, the small test ended up being quite easy to add.

#498 adds tests using the same task as the other attacks in `attacks.py`. Closing this because this seems to now be covered sufficiently.
