### ISSUE TITLE
Use a more reliable mirror for MNIST dataset

### ISSUE THREAD

**Issue by nottombrown** [tensorflow/cleverhans#496]
It looks like we are occasionally rejected from accessing the MNIST dataset from yann's website

https://travis-ci.org/tensorflow/cleverhans/jobs/416187998#L1223

Some possible options ordered by goodness:

- find a more reliable mirror of the dataset
- find a way to give the file to travis as a data asset
- upload the MNIST resource to gcs and make the bucket public

**Comment by npapernot** [comment]
One potential mirror is archive.org. For instance: https://web.archive.org/web/20150906081542/http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

**Comment by nottombrown** [comment]
This problem hasn't occurred again so I'm closing the issue.

**Comment by orlp** [comment]
Is a problem today.

**Comment by tejuafonja** [comment]
Thanks for letting us know @orlp. How can we replicate this problem that you encountered? Could you provide more details so we can further investigate it?

**Comment by orlp** [comment]
@tejuafonja Well I don't use this particular software package, but I got a similar root cause today when Google landed me here, so I thought I'd let you know. The URL <http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz> is giving out 503s sporadically today.

**Comment by tejuafonja** [comment]
Thanks for reporting this @orlp. We'll make the necessary changes.
