### ISSUE TITLE
Deprecation warnings are suppressed

### ISSUE THREAD

**Issue by nottombrown** [tensorflow/cleverhans#500]
We have two lines where we pass an explicit `DeprecationWarning` category to `warnings.warn`. It appears that passing that category causes the warning to not show up?

https://github.com/tensorflow/cleverhans/blob/3a70bf23039fc1269faef984244b2c0b530340ec/cleverhans/utils_tf.py#L34
https://github.com/tensorflow/cleverhans/blob/3a70bf23039fc1269faef984244b2c0b530340ec/cleverhans/utils_tf.py#L454

I'm not familiar with the code in question or how the warning system works, but I would suggest removing the category argument in order to get the warning to display to the user.

cc @david-berthelot who was the original author

**Comment by david-berthelot** [comment]
I don't know anything about it, I just copied it from elsewhere after being asked during review to add deprecation warnings.

**Comment by nottombrown** [comment]
Ok I will fix it
