### ISSUE TITLE
Let SPSA attack be called using `generate_np`

### ISSUE THREAD

**Issue by nottombrown** [tensorflow/cleverhans#502]
I spent some time this afternoon trying to get SPSA to hook into the `generate_np` harness, but had trouble getting it working. 

Currently the SPSA test works correctly using the `sess.run` syntax, but it would be slightly nicer to have it be callable with `generate_np`

https://github.com/tensorflow/cleverhans/pull/498/files#diff-ee72988b849d43f34dfd258c5f95fc8dR270

I also think that it would be good if SPSA could be called without any explicit labels (the default behavior for other classes is to use the models labels on the clean data as the label to attack in that case.

**Comment by nottombrown** [comment]
cc @juesato

**Comment by goodfeli** [comment]
This works now, maybe since #509?
