### ISSUE TITLE
error in mnist_tutorial_tf.py

### ISSUE THREAD

**Issue by mathcbc** [tensorflow/cleverhans#537]
I am trying to run mnist_tutorial_tf.py on Ubuntu 16.04 with Python 3.5.2 and TensorFlow 1.4 ,
but I am getting:

Traceback (most recent call last):
  File "/home/adv_attack_code/mnist_tutorial_tf.py", line 19, in <module>
    from cleverhans.loss import LossCrossEntropy
ImportError: No module named 'cleverhans.loss'

could you help me with it.
Thanks.

**Comment by goodfeli** [comment]
You probably have two copies of CleverHans installed. One is in your PYTHONPATH and gets imported when you execute import statements from inside the Python interpreter. The other one is not in your PYTHONPATH or doesn't have top priority within your PYTHONPATH, is the newer version, and is the version you're running.
