### ISSUE TITLE
Make tutorials check cleverhans.__path__

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#538]
It's common for users to install two versions of CleverHans and get confused when they run the tutorial from a new version and it fails to load new classes from the old version that takes precedence in their PYTHONPATH. We could cut down on this confusion a bit if we added a check from inside the CleverHans tutorials that the cleverhans module is in the same directory as the tutorial it is imported from.

**Comment by npapernot** [comment]
That's a good idea. We could warn the user that the tutorial is importing the CleverHans library from a directory that is different from the parent of the tutorial being executed.
