### ISSUE TITLE
overshoot does not work for DeepFool attack

### ISSUE THREAD

**Issue by mehdijj** [tensorflow/cleverhans#544]
Changing `overshoot` parameter does not have any effect in `DeepFool` attack. I think the problem is with `structural_kwargs` in `attack.py` file.
`over_shoot` should be changed to `overshoot`.

**Comment by npapernot** [comment]
@cihangxie  could you take a look?

**Comment by goodfeli** [comment]
@mehdijj are you using `generate` or `generate_np`? I think that, despite the bug, it should still have an effect when you use `generate`. (We should still fix the bug, I just want to make sure I understand what's going on)

**Comment by mehdijj** [comment]
@goodfeli I'm using `generate_np`

**Comment by cihangxie** [comment]
yes, we should change the variable from `over_shoot` to `overshoot`. Sorry for this mistake

**Comment by nottombrown** [comment]
@cihangxie are you interested in being the owner of this issue?
