### ISSUE TITLE
repeated download in utils_mnist.py

### ISSUE THREAD

**Issue by mathcbc** [tensorflow/cleverhans#568]
In line 31 of utils_mnist.py, `os.path.isfile(file_name)` is always equal to False, so the datasets downloaded from the Internet would not be saved to the local. Therefore, every time utils_mnist.py is ran, the datasets should be downloaded again.

This code didn't raise any error, but it would be better to avoid repeated download.

Thanks.

**Comment by nottombrown** [comment]
Good call. Closed by https://github.com/goodfeli/cleverhans/commit/6ae062639a7baddb1277b7b6bcbd22ca19b844eb
