### ISSUE TITLE
a problem about mnist_blackbox.py

### ISSUE THREAD

**Issue by hhhzzj** [tensorflow/cleverhans#572]
![problem](https://user-images.githubusercontent.com/37574973/45816803-4c79a600-bd0f-11e8-8d84-1261955f5525.png)

How should i do?

**Comment by hosna** [comment]
I am getting this 
    _sys.exit(main(argv))
  File "mnist_blackbox.py", line 292, in main
    lmbda=FLAGS.lmbda, aug_batch_size=FLAGS.data_aug_batch_size)
  File "mnist_blackbox.py", line 261, in mnist_blackbox
    rng, img_rows, img_cols, nchannels)
  File "mnist_blackbox.py", line 183, in train_sub
    args=eval_params)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
