### ISSUE TITLE
SPSA none shape error; mnist_tutorial_keras_tf.py

### ISSUE THREAD

**Issue by cvdeep** [tensorflow/cleverhans#577]
I'm getting the following error running mnist_tutorial_keras_tf.py with SPSA attack

 File "mnist_tutorial_keras_tf.py", line 247, in <module>
    tf.app.run()
  File "/Linux/Ubuntu/16.04/amd64/TOOLS/TENSORFLOW/1.8.0-GPU-PY2713/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "mnist_tutorial_keras_tf.py", line 233, in main
    load_model=FLAGS.load_model)
  File "mnist_tutorial_keras_tf.py", line 161, in mnist_tutorial
    adv_x = spsa.generate(x)
  File "/home/cleverhans/cleverhans/attacks.py", line 1829, in generate
    is_debug=is_debug,
  File "/home/cleverhans/cleverhans/attacks_tf.py", line 1859, in pgd_attack
    tf.shape(input_image), minval=-epsilon, maxval=epsilon, dtype=tf_dtype)
TypeError: bad operand type for unary -: 'NoneType'

**Comment by goodfeli** [comment]
Can you please post the exact code you're running? (You can attach a .py file to your comment, or you can link to a gist)

**Comment by npapernot** [comment]
In the code you shared, the call to `spsa.generate(x)` is missing some arguments. 

Just like other attacks (e.g., the ones in the tutorial), you need to pass some named arguments. For instance, I managed to get that line to execute by adding: 

```
spsa_params = {'epsilon': 0.3, 'y': tf.argmax(y, axis=1), 'num_steps': 5}
adv_x = spsa.generate(x, **spsa_params)
```

You will also need to have `x` have a batch size of 1, I will make a PR now to add a more friendly error when `x` does not have the right dimension.

**Comment by cvdeep** [comment]
@npapernot could you please elaborate where do you set the x to have batch size of 1,  specifically in the context of the mnist_tutorial_keras_tf.py file?

**Comment by cvdeep** [comment]
I managed to do it by commenting out the the following line in attacks_tf.py
`assert num_samples % 2 == 0, "number of samples must be even"`

and 

modifying `self._num_samples = num_samples // 2` to  `self._num_samples = num_samples`
