### ISSUE TITLE
"Retval[0] does not have value"  error while implementing JSMA

### ISSUE THREAD

**Issue by manjushree2012** [tensorflow/cleverhans#578]
### 
**Error : Retval[0] does not have value
Line:   `   adv_x = jsma.generate_np(sample,**jsma_params)**              `  

source_samples = X_test_scaled.shape[0]

# Keep track of success (adversarial example classified in target)
results = np.zeros((5, source_samples), dtype='i')

# Rate of perturbed features for each test set example and target class
perturbations =  np.zeros((5, source_samples), dtype='f')

#grads = jacobian_graph(predictions, x, 5)

X_adv = np.zeros((source_samples,X_test_scaled.shape[1]))

#Instantiate a SaliencyMethod attack object
jsma = SaliencyMapMethod(model, back='tf', sess = sess)

jsma_params = {
               'theta' : 1., 
               'gamma' : 0.1,
               'clip_min' : 0.,
               'clip_max': 1.0,
               'y_target': None
               }

print('Crafting adversarial test set examples')

# Loop over the samples we want to perturb into adversarial examples
for sample_ind in range(0, 1):
        print('--------------------------------------')
        print('Attacking input %i/%i' % (sample_ind + 1, source_samples))
       
        #current observation we want to perturbate
        sample = X_test_scaled[sample_ind:(sample_ind + 1)]
        
        #We want to find an adversarial example for each possible targeet class
        #(i.e. all classes that differ from the label given in the dataset)
        
        #return the index of first matched maximum value
        current_class = int(np.argmax(Y_test[sample_ind])) 
        
        target_classes = other_classes(5, current_class)
        
        #Loop over all target classes
        for target in target_classes:
                print('Creating adv. example for target class '+ str(target))
                
                if current_class == 1: #for normal attack
                        break
                
                one_hot_target = np.zeros((1, 5), dtype = np.float32)
                one_hot_target[0, target] = 1
                jsma_params['y_target'] = one_hot_target
                
                adv_x = jsma.generate_np(sample,**jsma_params)  `

**Comment by npapernot** [comment]
This seems related to #456, which was closed because it was not reproducible.  

Could you detail what changes you made from the JSMA tutorial? Did you change the model in addition to the data?

**Comment by npapernot** [comment]
Also can you post the full stack trace?

**Comment by manjushree2012** [comment]
**Changes I made from the JSMA tutorial :** 

I am trying to implement a MLP as my model. 


```
def mlp_model():
        model = Sequential()
        model.add(Dense(256, activation='relu', input_shape=(X_train_scaled.shape[1],)))
        model.add(Dropout(0.4))
        model.add(Dense(256, activation = 'relu'))
        model.add(Dropout(0.4))
        model.add(Dense(5, activation = 'softmax'))
        model.compile(loss = 'categorical_crossentropy',
                      optimizer = 'adam',
                      metrices = ['accuracy'])
        
        model.summary()
        
        return model
```

Whereas, **_mnist_tutorial_jsma.py_** tutorial has model 

```
 model = ModelBasicCNN('model1', nb_classes, nb_filters)
    preds = model.get_logits(x)
```

I am implementing my model as
```
model = mlp_model()
predictions = model(x)
```

This is the only change I brought from the _**mnist_tutorial_jsma.py**_ file.

**Comment by manjushree2012** [comment]
Here goes the full stack tree:
```
Traceback (most recent call last):

  File "<ipython-input-5-e54007f34bab>", line 54, in <module>
    adv_x = jsma.generate_np(sample,**jsma_params)

  File "F:\deeplearning\RNN\cleverhans-master\cleverhans\attacks.py", line 167, in generate_np
    return self.sess.run(x_adv, feed_dict)

  File "C:\Users\Jon Snow\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)

  File "C:\Users\Jon Snow\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\Jon Snow\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)

  File "C:\Users\Jon Snow\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Retval[0] does not have value
```

**Comment by npapernot** [comment]
Based on the syntax, I guess that you are using Keras to define the model? Have you wrapped the Keras model into a CleverHans model using https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_keras.py#L101

**Comment by manjushree2012** [comment]
I added this line in the previous source code.

`wrap = KerasModelWrapper(model)
`

Some changes were made to the code. Still, the ERROR remains the same. 

```
source_samples = X_test_scaled.shape[0]
results = np.zeros((5, source_samples), dtype='i')
perturbations =  np.zeros((5, source_samples), dtype='f')
X_adv = np.zeros((source_samples, X_test_scaled.shape[1]))
jsma = SaliencyMapMethod(wrap, back='tf', sess = sess)
jsma_params = {
               'theta' : 1., 
               'gamma' : 0.1,
               'clip_min' : 0.,
               'clip_max': 1.0,
               'y_target': None,
               'nb_classes' : 5
               }

print('Crafting adversarial test set examples')
for sample_ind in range(0, 1):
        print('--------------------------------------')
        print('Attacking input %i/%i' % (sample_ind + 1, source_samples))
       
        #current observation we want to perturbate
        sample = X_test_scaled[sample_ind:(sample_ind + 1)]
        
        #We want to find an adversarial example for each possible targeet class
        #(i.e. all classes that differ from the label given in the dataset)
        
        #return the index of first matched maximum value
        current_class = int(np.argmax(Y_test[sample_ind])) 
        
        target_classes = other_classes(5, current_class)
        
        #Loop over all target classes
        for target in target_classes:
                print('Creating adv. example for target class '+ str(target))
                
                if current_class == 1: #for normal attack
                        break
                
                one_hot_target = np.zeros((1, 5), dtype = np.float32)
                one_hot_target[0, target] = 1
                jsma_params['y_target'] = one_hot_target
                
                adv_x = jsma.generate_np(sample,**jsma_params)   
```
`

**Comment by npapernot** [comment]
Are you training the model with keras or tensorflow? Did you disable the keras learning phase before running the attack? 

It might be easier to modify the ModelBasicCNN example to remove the convolutions and add more fully connected layers.

**Comment by goodfeli** [comment]
Can you just post a .py file as an attachment or link to a gist that we can just run to reproduce the problem?

**Comment by manjushree2012** [comment]
### Attached file containing JSMA error. 


[jsma.txt](https://github.com/tensorflow/cleverhans/files/2412194/jsma.txt)


[dataset.zip](https://github.com/tensorflow/cleverhans/files/2412202/dataset.zip)

**Comment by npapernot** [comment]
I was able to have the script run without errors by adding the following line:

```
keras.layers.core.K.set_learning_phase(0)
```

You can find an example use here: https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_keras_tf.py
