### ISSUE TITLE
make tests for JSMA functionality

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#61]

**Comment by goodfeli** [comment]
I guess now there are tests for JSMA, but they're flaky? See the failure here: https://travis-ci.org/tensorflow/cleverhans/jobs/245472257

**Comment by npapernot** [comment]
Yes, I'd like to keep that open until we have more unit tests for the JSMA (and other attacks) and rely less on the somewhat flaky tutorial tests. Does that sound right?

**Comment by goodfeli** [comment]
k. Should we also make the tutorial tests less flaky somehow? Seeds for random number generators?

**Comment by npapernot** [comment]
Yes correct, I'll edit #176

**Comment by npapernot** [comment]
Closed by #198
