### ISSUE TITLE
Check for unused kwargs sent to attack.generate

### ISSUE THREAD

**Issue by nottombrown** [tensorflow/cleverhans#639]
I passed it an incorrect argument, and did not get a warning. Perhaps we should alert users when they have a typo in their kwargs?

**Comment by goodfeli** [comment]
I'm not sure about this specific use of kwargs, but in a lot of places we're using kwargs as an explicit non-interface. For example, you can pass basically anything to MLP.fprop and maybe some Layer subclass will pick it up and maybe nothing will pick it up. The upside is that it makes it easy to make exotic new layers that behave differently in different contexts without needing to make the MLP class aware of all those different contexts. The downside is that there isn't any way I'm aware of to detect errors like this kind of typo. If we can come up with a better design we definitely should, but it's not as simple as just adding a one-line check somewhere.

**Comment by goodfeli** [comment]
(Oh, and we should check whether it is feasible to check the kwargs for Attack.generate, I'm not sure if that specific use of kwargs is one of the ones that's hard to validate)

**Comment by nottombrown** [comment]
Hmm I had thought that this would be easy because we already explicitly list the different types of  kwargs for `generate_np`. 
```
    # When calling generate_np, arguments in the following set should be
    # fed into the graph, as they are not structural items that require
    # generating a new graph.
    # This dict should map names of arguments to the types they should
    # have.
    # (Usually, the target class will be a feedable keyword argument.)
    self.feedable_kwargs = {}

    # When calling generate_np, arguments in the following set should NOT
    # be fed into the graph, as they ARE structural items that require
    # generating a new graph.
    # This list should contain the names of the structural arguments.
    self.structural_kwargs = []
```

However, it looks like there are a few places where kwargs don't fall into either `feedable_kwargs` or `structural_kwargs`. For example the `rand_minmax` kwarg here:
https://github.com/tensorflow/cleverhans/blob/aa1033a98609c96f6626897fb882219f591a7db3/cleverhans/attacks.py#L489

If we think that all `generate_np` kwargs should always be either `feedable` or `structural`, then I think it would be fairly straightforward to do this. If not, then I'm not sure if this is worthwhile.

**Comment by goodfeli** [comment]
Yes, that seems worth doing. I misunderstood what you meant earlier. I believe it's possible to catch unused keywords when they're passed to `generate_np` because those calls all pass through the base class's graph caching mechanism. Earlier I thought you meant a call to `generate`. That seems hard because each subclass implements its own `generate` and doesn't usually call through a centralized piece of code.

**Comment by goodfeli** [comment]
Done in this PR: https://github.com/tensorflow/cleverhans/issues/639
