### ISSUE TITLE
reactivate test_attack_strength for spatial transformation attack

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#704]
I disabled the test because it was flaky and does not seem to be making the right calls to the model interface

**Comment by npapernot** [comment]
The old test is here: https://github.com/tensorflow/cleverhans/pull/635/commits/49b3c75f0d0d3b65b1d9460794c198c4bfe582a6

**Comment by nottombrown** [comment]
That test can stay removed because we have new tests.
