### ISSUE TITLE
Typo in UnrolledOptimizer

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#778]
What is a "functional-stype optimizer"? I'm not sure if this is a term I haven't heard before or a typo for "functional-type optimizer".

**Comment by juesato** [comment]
Should read "functional-style optimizer," since it is stateless and does not use tf.Variable objects.

Would you prefer this docstring? "Optimizer for Tensors rather than tf.Variables."

**Comment by goodfeli** [comment]
Yes, I prefer the new proposal for the docstring, thanks.

**Comment by robert-wagner** [comment]
This should be closed as it is resolved
