### ISSUE TITLE
Why do UnrolledOptimizers use while loops?

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#779]
See for example SPSAAdam, which is an UnrolledOptimizer but uses tf.while_loop. I suspect "UnrolledOptimizer" is just not named very well, and should have a name that reflects that it does not use Variables rather than a name that implies it unrolls loops.

**Comment by juesato** [comment]
It sounds like you already know this, but just for completeness: there's two levels of loops at play here:
1. The outer while loop, for multiple iterations of optimization (as in PGD, or any other iterative attack).
2. An inner while loop, used for computational reasons in SPSA. Each outer iteration requires evaluating the model on N inputs. If N is larger than the number of model activations we can fit in memory (for example, for big Imagenet models), then we do this computation inside a `tf.while_loop`.

No strong preference on the name `UnrolledOptimizers` from me.

**Comment by goodfeli** [comment]
@juesato is it OK with you if I rename `UnrolledOptimizer` to `TensorOptimizer` or `FunctionalOptimizer`?

**Comment by juesato** [comment]
Either is fine by me, very slight preference for `TensorOptimizer`.
