### ISSUE TITLE
adversarial embedding export

### ISSUE THREAD

**Issue by snailexe** [tensorflow/cleverhans#783]
I am fresh to the tensorflow and cleverhans. I was trying to follow the tutorial https://github.com/tensorflow/cleverhans/tree/master/examples/facenet_adversarial_faces. But after I get the adv, how should I restore the images from those adversarial embeddings.  Should I use the exporting_embedding.py in facenet?

**Comment by goodfeli** [comment]
We use the github issues for tracking work that needs to be done, not for general support. I don't know the answer to this question myself. You could write to cleverhans-dev@googlegroups.com to see if anyone else knows.
