### ISSUE TITLE
Adversarial image not clipped for first iteration of PGD (MadryEtAl)

### ISSUE THREAD

**Issue by vipinpillai** [tensorflow/cleverhans#823]
As part of the ProjectedGradientDescent attack, when used with default_rand_init=True, _eta_ is initialized with random noise [here](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks.py#L508) and then clipped within L-infinity norm of _eps_.
However, when the the adversarial image is fed to the PGD attack for the very first iteration, [x+e](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks.py#L547) is not clipped to lie in the valid image range.

This shouldn't significantly affect the PGD adversarial attack results though since it is only the first iteration which doesn't provide meaningful gradients.

**Comment by goodfeli** [comment]
Thanks, good catch!
