### ISSUE TITLE
Check why pylint did not catch call to jsma_batch in attacks.py (jsma_batch does not exist anymore)

### ISSUE THREAD

**Issue by erfannoury** [tensorflow/cleverhans#872]
`jsma_batch` is used in `attacks.py` code in the following lines:
https://github.com/tensorflow/cleverhans/blob/539223ae33ca4f416e1cc08c533fec3982bd2aad/cleverhans/attacks.py#L924-L965
However, this method no longer exists in `attacks_tf.py`.

**Comment by erfannoury** [comment]
I don't need it. I was just going over the code and realized that it might be a bug in the code.

**Comment by goodfeli** [comment]
It's also worth checking why pylint didn't catch this

**Comment by redshiftzero** [comment]
this issue wasn't caught by pylint due to `E0611` being disabled, if you re-enable you will see:

```
cleverhans/attacks/__init__.py:964: [E0611(no-name-in-module), SaliencyMapMethod.generate] No name 'jsma_batch' in module 'cleverhans.attacks_tf'
```
