### ISSUE TITLE
Issue when starting cleverhans_tutorial on MAC OS X

### ISSUE THREAD

**Issue by stoneyang** [tensorflow/cleverhans#875]
Hi, there:

After installed cleverhans by `pip install cleverhans --user` on my machine, I'd like to run a tutorial to see if everything's ok. Unfortunately, I received the following error mesage after running `python mnist_tutorial_tf.py`:

```
Traceback (most recent call last):
  File "mnist_tutorial_tf.py", line 19, in <module>
    from cleverhans.loss import CrossEntropy
ModuleNotFoundError: No module named 'cleverhans.loss'
```

Then I checked the version by `python -c 'import cleverhans; print(cleverhans.__version__)` and the version number is `2.0.0-8d4c955f2a5a269a78a612198cf754a4`. 

When running the trouble line `from cleverhans.loss import CrossEntropy` in the console, same error exists! So, anyone could help? Thanks.

**Comment by stoneyang** [comment]
When using python2.7, I get:
```
Traceback (most recent call last):
  File "mnist_tutorial_tf.py", line 19, in <module>
    from cleverhans.loss import CrossEntropy
ImportError: No module named loss
```

**Comment by goodfeli** [comment]
If you just want to get cleverhans working, the easiest way is to use "git clone" and set your PYTHONPATH manually. That's how I always install.

We know that `pip` tends to install `cleverhans` in weird locations that are not on the `PYTHONPATH`. None of the main `cleverhans` developers including myself know enough about `pip` or `setup.py` to tell exactly what is going wrong. If you could tell us where `pip` does put cleverhans on your Mac, that might help us. Alternately, if anyone who does understand `pip` and `setup.py` happens to see this issue, we could use your help.

**Comment by npapernot** [comment]
Another possibility is that we have not updated pypi in a long time (because we updated pypi when incrementing Cleverhans to 2.0) and for that reason the loss module might not have existed at that time.

**Comment by goodfeli** [comment]
What happens if you run `python -c "import cleverhans"`? If that fails then the whole library is not installed on the `PYTHONPATH`.

How did you install the tutorials? Did they come from the same `pip` command as the library?

**Comment by stoneyang** [comment]
> If you just want to get cleverhans working, the easiest way is to use "git clone" and set your PYTHONPATH manually. That's how I always install.
> 
> We know that `pip` tends to install `cleverhans` in weird locations that are not on the `PYTHONPATH`. None of the main `cleverhans` developers including myself know enough about `pip` or `setup.py` to tell exactly what is going wrong. If you could tell us where `pip` does put cleverhans on your Mac, that might help us. Alternately, if anyone who does understand `pip` and `setup.py` happens to see this issue, we could use your help.

Sorry for the late reply. I adopted your suggestion and clouds gone, both on Mac and linux.

**Comment by duoergun0729** [comment]
i the same 
python -c 'import cleverhans; print(cleverhans.__version__)'
2.0.0-8d4c955f2a5a269a78a612198cf754a4

but 

python -c "from cleverhans.loss import CrossEntropy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cleverhans.loss'

i install use   pip install cleverhans

**Comment by duoergun0729** [comment]
and path is ;
/mnt/opt/anaconda2/envs/book5/lib/python3.6/site-packages/cleverhans

**Comment by duoergun0729** [comment]
i know why 。there is some wrong with setup.py

git clone https://github.com/tensorflow/cleverhans

cp -fr cleverhans cleverhans_tutorials /mnt/opt/anaconda2/envs/book5/lib/python3.6/site-packages/

can solve it
