### ISSUE TITLE
Use Keras' custom losses in mnist_tutorial_keras_tf.py

### ISSUE THREAD

**Issue by batzner** [tensorflow/cleverhans#895]
I was reading the `mnist_tutorial_keras_tf.py` and wondered if it could be simplified by using Keras' custom losses. For example, the following code runs as fast as the tutorial in both CPU and GPU mode:

```python
model = Sequential([
    ...
])

def loss(labels, logits):
    # Compute the cross-entropy on the legitimate examples
    cross_ent = tf.losses.softmax_cross_entropy(labels, logits)

    # Compute the adversarial examples
    gradients, = tf.gradients(cross_ent, model.input)
    inputs_adv = tf.stop_gradient(model.input + 0.3 * tf.sign(gradients))

    # Compute the cross-entropy on the adversarial examples
    logits_adv = model(inputs_adv)
    cross_ent_adv = tf.losses.softmax_cross_entropy(labels, logits_adv)

    return 0.5 * cross_ent + 0.5 * cross_ent_adv

model.compile(optimizer='adam', loss=loss)
model.fit(x_train, y_train, ...)
```

Is there any downside to using custom losses that I am missing? I think it would make the tutorial a bit more accessible to Keras users, as they could stick to the `compile` and `fit` functions of Keras models. I'd be happy to submit a pull request if you think it is appropriate.

**Comment by goodfeli** [comment]
That seems OK to me.

**Comment by npapernot** [comment]
Thanks for looking into this. At the time where we wrote the tutorial, it was difficult to use Keras' fit function because it then required that we pass Keras' backend learning_phase to each sess.run in CleverHans (for instance when calling model_eval or batch_eval). If this is not the case anymore, it would be good to make the tutorial more Keras-like so it is more accessible to Keras users.

**Comment by npapernot** [comment]
@batzner  would you still like to make a PR for this or should I close this issue for now?

**Comment by batzner** [comment]
@npapernot please excuse the slow reply - I have opened a PR here: https://github.com/tensorflow/cleverhans/pull/962
