### ISSUE TITLE
Missing affiliations for contributors (needed to credit contributions in the tech report)

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#899]
If you are tagged below, could you respond with your current affiliation? 

@aashish-kumar 
@aspratyush
@BrunoLopezGarcia

**Comment by aashish-kumar** [comment]
Hi Papernot,

Adding my Affiliation
@aashish-kumar  HARMAN X

**Comment by aspratyush** [comment]
Adding my affiliation:
@aspratyush ex-HARMAN X

**Comment by npapernot** [comment]
@BrunoLopezGarcia any update? We will be pushing out a tech report without an affiliation otherwise
