### ISSUE TITLE
InceptionResnetV1Model' must implement `get_logits` or must define a logits output in `fprop`

### ISSUE THREAD

**Issue by cishwarya** [tensorflow/cleverhans#902]
Hello all,

I am trying to generate FGSM attack on Facenet. 
When I execute "facenet_fgsm.py", I am getting the error "implement `get_logits` or must define a logits output in `fprop`". (please see below)
I am a newbie could someone please help me here?

Please let me know if you require any additional details

Error:
Traceback (most recent call last):
  File "facenet_fgsm.py", line 89, in <module>
    adv_x = fgsm.generate(model.face_input, **fgsm_params)
  File "/home/sysgen/anaconda2/envs/facenet/lib/python3.5/site-packages/cleverhans/attacks.py", line 348, in generate
    self.model.get_logits(x),
  File "/home/sysgen/anaconda2/envs/facenet/lib/python3.5/site-packages/cleverhans/model.py", line 74, in get_logits
    " output in `fprop`")
NotImplementedError: <class '__main__.InceptionResnetV1Model'>must implement `get_logits` or must define a logits output in `fprop`

**Comment by goodfeli** [comment]
`fprop` returns a dictionary mapping from string names of layers to their TensorFlow values. Your `InceptionResNetV1Model` looks like it implements `fprop` but the dict it returns doesn't have a `logits` key in it. You need to change your `fprop` implementation to include the `logits` key.
