### ISSUE TITLE
How can I change cleverhans.train to scikitlearn Random Forest in mnist_blackbox.py

### ISSUE THREAD

**Issue by Jeredriq** [tensorflow/cleverhans#909]
```
 # Train an MNIST model
  train_params = {
      'nb_epochs': nb_epochs,
      'batch_size': batch_size,
      'learning_rate': learning_rate
  }
  train(sess, loss, x_train, y_train, args=train_params, rng=rng)
```

I understand this part but what I'm trying to achieve is to train it with scikitlearn Random Forest like: 

```
model = RandomForestClassifier(max_depth=args.max_dep,
                                       n_estimators=args.n_est,
                                       max_features=None,
                                       n_jobs=-1)
```

Any suggestion how can I do that? Sorry if its a stupid question, I am a newbie

**Comment by npapernot** [comment]
The training module in CleverHans works with models defined using TensorFlow so you would have to redefine your random forest with TensorFlow first. The issue tracker is only for bugs or feature requests, so I encourage you to ask your question or similar questions on StackOverflow in the future.

**Comment by Jeredriq** [comment]
@npapernot its not about this topic but when I tried to run mnist_blackbox.py I've got 'tuple' object has no attribute 'get_set' error. at  x_train, y_train = mnist.get_set('train') line from mnist_blackbox function
