### ISSUE TITLE
Run time getting a lot slower

### ISSUE THREAD

**Issue by B-Yassine** [tensorflow/cleverhans#910]
Dear all,
I just upgraded to cleverhans 2.1.0 version and it seems like the attacks are getting a lot slower for instance a Pgd attack was taking only 10 mn to generate the adversarial image but now it is taking about an hour and a half to generate it and I could not downgrade to 2.0.0 as it doesn't exist anymore in pypi 

Is there an explanation for this problem, is it a problem with the tensorflow's graph generation?

I am using tensorflow version : 1.12.0
Cleverhans version: 2.1.0
Python version: 3.6

**Comment by goodfeli** [comment]
You can always download by manually cloning the early github tag.

I don't actually know about pypi. @npapernot should the old version actually be removed from pypi?

@B-Yassine : this kind of slowdown isn't expected. Are you sure you're using the same model and the same configuration for the attack (especially the number of iterations) as before? Has the attack moved from running on GPU to running on CPU?

**Comment by npapernot** [comment]
I responded to @B-Yassine's email and just saw this. For everyone else reading this: the old version is still in pypi: 

* current version (v3): https://pypi.org/project/cleverhans/3.0.0.post0/
* older version (v2.1): https://pypi.org/project/cleverhans/2.1.0/

**Comment by B-Yassine** [comment]
Yes, the old version 2.1.0 is still in pypi and you can get it simply by
running:
pip3 install cleverhans==2.1.0

Thank you for your responds

Best

**Comment by goodfeli** [comment]
Do you still want us to help debug the slowness in v3?

**Comment by B-Yassine** [comment]
Yes, of course because am very interested in this domain as I am preparing
my Master thesis and being able to contribute will be a honor for me.

I think there's another problem with the deepfool attack as I tried there
source code implemented in Pytorch and using the cleverhans implementation
with the same parameters and the same model "inception v3" and the results
where differents !

The author told me that he doesn't know about the cleverhans implementation
and adviced me to use its own implementation

Best,
Yassine

**Comment by B-Yassine** [comment]
For the deepfool attack i think it has to be opened as another issue

**Comment by goodfeli** [comment]
Yes, please open another issue with more detail for the deepfool attack.

**Comment by goodfeli** [comment]
Do you still want to try to debug the slowness issue?

**Comment by B-Yassine** [comment]
Thanks a lot so the problem has been resolved by downgrading to the previous version 2.1.0 and it can be done by running:
pip install cleverhans==2.1.0 and making sure it is running on gpu
