### ISSUE TITLE
AttributeError: 'float' object has no attribute 'dtype' 

### ISSUE THREAD

**Issue by JolyLei** [tensorflow/cleverhans#916]
AttributeError: 'float' object has no attribute 'dtype'.     
python3.5/site-packages/cleverhans/attacks.py", line 620, in generate
    dtype=self.eps.dtype)
when I run BasicIterativeMethod to craft BIM adversarial example,  with params     bim_paras = {
                    'clip_min': 0.,
                    'clip_max': 1.,
                   'y_target': None
    }

i just comment out this line..........................  and it run correctly..

win10&ubuntu   python3.5

**Comment by goodfeli** [comment]
If you installed via pip, upgrade to 3.0.1, or if you installed with git, pull the latest master. This is a bug that was introduced recently and fixed recently.
