### ISSUE TITLE
Generating adversarial data from cleverhans attack models

### ISSUE THREAD

**Issue by Jeredriq** [tensorflow/cleverhans#931]
I want a code example to how to generate train data from clever hans' adversarial attacks.

`adv_x = fgsm.generate_np(X_test, **fgsm_params)`

This generates adversarial x data but how can I get y?

 `adv_pred = model.predict_classes(adv_x)`

And this will give the "fooled" results right?

What I want is to correctly show generated x, y, fooled y (by which I mean results of models predictions that may be false because of the attack). I'm using Mnist btw, if it helps.

**Comment by npapernot** [comment]
Thank you for asking this question on StackOverflow, there is no need to double post.
