### ISSUE TITLE
'fprop' not implemented error in atack_fgsm.py

### ISSUE THREAD

**Issue by Uno-Takashi** [tensorflow/cleverhans#933]
I have thought about re-implementing "universal adversarial perturbation" using a trained model and cleverhans. As the previous stage, I searched for a examples that uses trained model to output something Adversarial Examples.

For that reason, I've tried using attack_fgsm.py from nips17_adversarial_competition. 
https://github.com/tensorflow/cleverhans/blob/master/examples/nips17_adversarial_competition/dev_toolkit/sample_attacks/fgsm/attack_fgsm.py

foremost,I made changes to the directory as follows.

|- fgsm
&nbsp;&nbsp;&nbsp;|-- input
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---(( some images ))
&nbsp;&nbsp;&nbsp;|-- output
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--- ((empty directory))
&nbsp;&nbsp;&nbsp;|-- inception_v3.ckpt
&nbsp;&nbsp;&nbsp;|-- atack_fgsm.py
&nbsp;&nbsp;&nbsp;|-- metadata.json
&nbsp;&nbsp;&nbsp;|-- run_attack.sh

Next, I fixed part of attack_fgsm.py as follows.

```
tf.flags.DEFINE_string(
    'master', '', 'The address of the TensorFlow master to use.')

tf.flags.DEFINE_string(
    'checkpoint_path', 'inception_v3.ckpt', 'Path to checkpoint for inception network.')

tf.flags.DEFINE_string(
    'input_dir', 'input/', 'Input directory with images.')

tf.flags.DEFINE_string(
    'output_dir', 'output/', 'Output directory with images.')
```

I execution attack_fgsm.py in this state and the following error appeared.

```
`fprop` not implemented.
stack trace:
 >  File "G:\downloads\cleverhans-master\cleverhans-master\examples\nips17_adversarial_competition\dev_toolkit\sample_attacks\fgsm\attack_fgsm.py", line 160, in main
 >    save_images(adv_images, filenames, FLAGS.output_dir)
 >  File "G:\downloads\cleverhans-master\cleverhans-master\examples\nips17_adversarial_competition\dev_toolkit\sample_attacks\fgsm\attack_fgsm.py", line 164, in <module>
 >    tf.app.run()
'__main__' を読み込みました
'tensorflow.python.platform.app' を読み込みました
Backend TkAgg is interactive backend. Turning interactive mode on.
```

The program is stopped at the following location.
https://github.com/tensorflow/cleverhans/blob/510e16df371f006ded96ad7fbae7486653897aba/examples/nips17_adversarial_competition/dev_toolkit/sample_attacks/fgsm/attack_fgsm.py#L145

How can I resolve this error?

**Comment by goodfeli** [comment]
I'm pretty sure that's not the full stack trace or error message, can you paste all of it?

**Comment by Uno-Takashi** [comment]
Sorry. This problem was caused by the change of InceptionModel inheritance from object class to Model class.

But, when I undo this change I got a new error.
```
G:\fgsm>py.exe attack_fgsm.py
Traceback (most recent call last):
  File "attack_fgsm.py", line 161, in <module>
    tf.app.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "attack_fgsm.py", line 144, in main
    fgsm = FastGradientMethod(model)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\cleverhans\attacks\__init__.py", line 328, in __init__
    super(FastGradientMethod, self).__init__(model, sess, dtypestr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\cleverhans\attacks\__init__.py", line 57, in __init__
    raise TypeError("The model argument should be an instance of"
TypeError: The model argument should be an instance of the cleverhans.model.Model class.
```
I guess this is due to the inheritance class of the following line, how can i fix.

https://github.com/tensorflow/cleverhans/blob/510e16df371f006ded96ad7fbae7486653897aba/examples/nips17_adversarial_competition/dev_toolkit/sample_attacks/fgsm/attack_fgsm.py#L98

**Comment by goodfeli** [comment]
@AlexeyKurakin do you have any opinions? I think what's going on is that this `examples` directory was made before we started using the `Model` class consistently as part of the `Attack` definitions. Do we want to keep updating this example to work with newer versions of the library? Or do we want to leave it as a snapshot of the code that was actually used for NIPS 2017 and give instructions for how to install a compatible, older version of CleverHans?

**Comment by DongyangZhang** [comment]
Hello,i get the same problem with"NotImplementedError: `fprop` not implemented."  i saw you question,but it's still not work, i change 'object' to 'Model',What shuold i do next step???Thank!!

**Comment by npapernot** [comment]
The model object should implement a class `fprop` that computes the model’s outputs for a given input (the forward pass). The example code referred to above was likely written before a model class was added so that’s why you would have to wrap it properly in a model class. You can find an example here: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/model_zoo/all_convolutional.py
