### ISSUE TITLE
Frozen weights

### ISSUE THREAD

**Issue by choltz95** [tensorflow/cleverhans#934]
Hi, I am following the MNIST Keras tutorial. My goal is to implement a random projection layer by initializing the weights of a dense layer to a sparse random matrix.

Eventually, I want to be able to freeze the weights which are initially zero. However, I can't seem to get any layer at all, or even the model, to have frozen weights. I have tried applying both tf.stop_gradient to the weight tensor and setting the trainable parameter of my Keras layers to false. However, the parameters are still being trained.

Is there any advice to go about solving this problem? I guess my issue involves the train.py script.

**Comment by npapernot** [comment]
This type of question is best asked on StackOverflow so others can help provide an answer: https://stackoverflow.com/search?q=cleverhans

In the meanwhile, I would suggest looking at the `var_list` argument of the `train` function. I'll close this issue but feel free to discuss further on StackOverflow unless you'd like to make a feature request or report a bug. Thank you!
