### ISSUE TITLE
Cleverhans documentation is not showing attacks

### ISSUE THREAD

**Issue by npochhi** [tensorflow/cleverhans#944]
Cleverhans docs' attack list page [here](https://cleverhans.readthedocs.io/en/latest/source/attacks.html), is currently empty.

![image](https://user-images.githubusercontent.com/13417114/50969965-0aff4780-1506-11e9-8f38-af928587a7d3.png)

**Comment by npapernot** [comment]
@nottombrown did you get a chance to take a look at the isssue?

**Comment by goodfeli** [comment]
I imagine this is because I recently moved each attack into its own submodules. @nottombrown , is there something I need to do to register the new submodules with the doc system?

**Comment by npapernot** [comment]
@nottombrown could you give me rights to the CleverHans readthedocs project so I can take a look? My account is npapernot

**Comment by npapernot** [comment]
@nottombrown gentle ping

**Comment by nottombrown** [comment]
Ah sorry for the slow response. It looks like my github updates were being filtered. @npapernot I've added you as a maintainer of the readthedocs project here: https://readthedocs.org/dashboard/cleverhans/

**Comment by npapernot** [comment]
Thanks a lot @nottombrown, I was able to fix the issue!
