### ISSUE TITLE
from cleverhans.compat import flags doesn't work

### ISSUE THREAD

**Issue by AditAg** [tensorflow/cleverhans#960]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
from cleverhans.compat import flags
When I run this in Python, I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'flags'

**To Reproduce**

**Expected behavior**

**Screenshots**

**System configuration**
 - OS - Ubuntu 16.04
 - Python version - 3.6.3 (anaconda installed)
 - TensorFlow version - 1.12.0

**Comment by npapernot** [comment]
Are you using the latest version of CleverHans? I was able to run the following script from my machine by pulling from the master branch:

```
from cleverhans.compat import flags
```

**Comment by AditAg** [comment]
The version is 3.0.1. Actually, I installed the library using pip today itself. I have attached the screenshot for your reference.
![image](https://user-images.githubusercontent.com/22225079/51554448-5832d000-1e9b-11e9-8fc5-e7509a83155d.png)

**Comment by npapernot** [comment]
The version for pip is not the latest (it doesn't keep track of each commit to the master branch but rather is the last versioned CleverHans), could you try installing by cloning the github repository directly? You can do it with `pip install git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans`

**Comment by AditAg** [comment]
I uninstalled the library and then, upgraded the version of pip to 19.0.1. Then when I installed cleverhans using  pip install git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans, it worked. 
Thanks for the help.

**Comment by shamoons** [comment]
I can't do `pip install git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans` for some reason

I get `no matches found: git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans`

**Comment by tanjuntao** [comment]
> The version for pip is not the latest (it doesn't keep track of each commit to the master branch but rather is the last versioned CleverHans), could you try installing by cloning the github repository directly? You can do it with `pip install git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans`

It works! Thanks for your kind help!
