### ISSUE TITLE
Can we add CarliniWagnerL0 and CarliniWagnerL1 attacks?

### ISSUE THREAD

**Issue by Shawn-Shan** [tensorflow/cleverhans#978]
**Describe the solution you'd like**
I would like to have L0 and L1 version of CW attack in addition to the L2 version. 

**Describe alternatives you've considered**
I have looked into the original code repo of the SP17 paper, which has L0 and L1 version, but I would like to have those in cleverhans as well. 

**Additional context**
I assume it wouldn't be that hard to add the addition CW attacks. As one of the most powerful attack, I suggest that Cleverhans can support all of its variance. Thanks!

**Comment by goodfeli** [comment]
@carlini ?

**Comment by GuanxiongLiu** [comment]
I'm also looking for the solutions required in this post. Currently, I'm trying to see if I can mitigate the original li CW attack from https://github.com/carlini/nn_robust_attacks/blob/master/li_attack.py locally.

**Comment by carlini** [comment]
By L1 do you mean l_infinity? I haven't done a L1 attack. Or EAD is a L1 optimization-based attack? Do you mean that?

L0 sure. It still performs reasonably well. At one point I started moving it over to cleverhans but never finished. If it would be helpful I can do that. I personally no longer use the l_infinity attack as described in the paper. I didn't l_infinity regularize the gradients which in retrospect is clearly the right thing to do most of the time. Using l_infinity regularized PGD is faster and so far I've never seen it do worse, so I would prefer *not* to add it.

**Comment by Shawn-Shan** [comment]
Yes, I mean L_infinity and L0. 

I am working on a defense paper, and I would like to evaluate against all the attacks. 

It will be great you can add those two attacks, thanks!

**Comment by carlini** [comment]
When I get a chance I'll add L_0. For now I do have code available here: https://github.com/carlini/nn_robust_attacks you can use

One word of unsolicited advice: please think carefully when applying these other attacks. I would much rather see an evaluation against only PGD than an evaluation that tried PGD as well as many other attacks, but just running the code for those.

**Comment by Shawn-Shan** [comment]
Thanks for the advice!
