### ISSUE TITLE
when I degisn a network to get adversarial samples using mnist_tutorial_jsma.py, tf.nn.log_softmax does not work, but tf.nn.softmax works

### ISSUE THREAD

**Issue by zhouxiaowei1120** [tensorflow/cleverhans#980]
when I degisn a network to get adversarial samples using mnist_tutorial_jsma.py, if I use tf.nn.log_softmax at the last layer, it does not work and gives the errors(As followed). But if I use tf.nn.softmax, it works without any bugs.

Please see here in detail: 

Here is the network, it does not work.

```
class ModellenetCNN(Model):
  def __init__(self, scope, nb_classes, **kwargs):
    del kwargs
    Model.__init__(self, scope, nb_classes, locals())
    # self.nb_filters = nb_filters

    # Do a dummy run of fprop to make sure the variables are created from
    # the start
    self.fprop(tf.placeholder(tf.float32, [128, 28, 28, 1]))
    # Put a reference to the params in self so that the params get pickled
    self.params = self.get_params()

  def fprop(self, x, **kwargs):
    del kwargs
    my_conv = functools.partial(
        tf.layers.conv2d, activation=tf.nn.relu,
        kernel_initializer=initializers.HeReLuNormalInitializer)
    with tf.variable_scope(self.scope, reuse=tf.AUTO_REUSE):
      y = my_conv(x, 20, 5, strides=1, padding='valid')
      y = tf.layers.max_pooling2d(y,2,2)
      y = my_conv(y, 50, 5, strides=1, padding='valid')
      y = tf.layers.max_pooling2d(y,2,2)
      y = tf.layers.dense(
          tf.layers.flatten(y), 500,
          activation=tf.nn.relu,
          kernel_initializer=initializers.HeReLuNormalInitializer)
      logits = tf.layers.dense(
         y, self.nb_classes,
          kernel_initializer=initializers.HeReLuNormalInitializer)
      return {self.O_LOGITS: logits,
              self.O_PROBS: tf.nn.log_softmax(logits=logits)}
```

THe error is:

```
assertion failed: [] [Condition x >= y did not hold element-wise:x (while/Min:0) = ] [-5.21570587] [y (while/Cast/x:0) = ] [0]    [[Node: while/assert_greater_equal/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/assert_greater_equal/Assert/AssertGuard/Assert/Switch, while/assert_greater_equal/Assert/AssertGuard/Assert/data_0, while/assert_greater_equal/Assert/AssertGuard/Assert/data_1, while/assert_greater_equal/Assert/AssertGuard/Assert/Switch_1, while/assert_greater_equal/Assert/AssertGuard/Assert/data_3, while/assert_greater_equal/Assert/AssertGuard/Assert/Switch_2)]]  Caused by op 'while/assert_greater_equal/Assert/AssertGuard/Assert', defined at:   
```

For this network, it works fine:

```
class ModellenetCNN(Model):
  def __init__(self, scope, nb_classes, **kwargs):
    del kwargs
    Model.__init__(self, scope, nb_classes, locals())
    # self.nb_filters = nb_filters

    # Do a dummy run of fprop to make sure the variables are created from
    # the start
    self.fprop(tf.placeholder(tf.float32, [128, 28, 28, 1]))
    # Put a reference to the params in self so that the params get pickled
    self.params = self.get_params()

  def fprop(self, x, **kwargs):
    del kwargs
    my_conv = functools.partial(
        tf.layers.conv2d, activation=tf.nn.relu,
        kernel_initializer=initializers.HeReLuNormalInitializer)
    with tf.variable_scope(self.scope, reuse=tf.AUTO_REUSE):
      y = my_conv(x, 20, 5, strides=1, padding='valid')
      y = tf.layers.max_pooling2d(y,2,2)
      y = my_conv(y, 50, 5, strides=1, padding='valid')
      y = tf.layers.max_pooling2d(y,2,2)
      y = tf.layers.dense(
          tf.layers.flatten(y), 500,
          activation=tf.nn.relu,
          kernel_initializer=initializers.HeReLuNormalInitializer)
      logits = tf.layers.dense(
         y, self.nb_classes,
          kernel_initializer=initializers.HeReLuNormalInitializer)
      return {self.O_LOGITS: logits,
              self.O_PROBS: tf.nn.softmax(logits=logits)}
```

Could you fix this? thank you.

**Comment by npapernot** [comment]
This is most likely related to #853, I am working on a PR that will switch the Jacobian computation from the probabilities to the logits.

**Comment by zhouxiaowei1120** [comment]
> This is most likely related to #853, I am working on a PR that will switch the Jacobian computation from the probabilities to the logits.

Ok. Thank you for your effort.

**Comment by npapernot** [comment]
Let me know if #982 fixes it

**Comment by zhouxiaowei1120** [comment]
Another question: Could I generate adversarial samples usiing  trained models on pytorch in mnist_tutorial_jsma.py? I modified mnist_tutorial_jsma.py according to mnist_tutorial_pytorch.py, but it does not work, wich gives the error:

AttributeError: 'NoneType' object has no attribute 'cpu' Traceback (most recent call last):    File "/home/uts/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__     ret = func(*args)    File "/media/uts/Windows/Users/12882357/Desktop/research/R_generation/cleverhans/cleverhans/utils_pytorch.py", line 73, in _bprop_fn     return torch_state['x'].grad.cpu().data.numpy()  AttributeError: 'NoneType' object has no attribute 'cpu'      [[Node: while/gradients_9/while/PyFunc_grad/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_11", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/Identity, while/gradients_9/while/Softmax_grad/mul_1)]]  Caused by op 'while/gradients_9/while/PyFunc_grad/PyFunc', defined at:

Could you tell me the reason? Thank you .

**Comment by npapernot** [comment]
I've never used PyTorch so I don't really know how to help here. I think @david-berthelot or @nottombrown might know more about this. If you could post questions like this on StackOverflow (https://stackoverflow.com/questions/tagged/cleverhans) rather than this issue tracker, that would be best unless you find a reproducible bug in the library.
