### ISSUE TITLE
Why cannot I prepare fprop graph in Model.__init__()?

### ISSUE THREAD

**Issue by cloudseasail** [tensorflow/cleverhans#993]
I donot like to compute the graph in Model.fprop() everytime, why cannot I prepare the graph in Model.__init__()?  It seems have issue with this approach.

```
class MyModel(Model):
    def __init__(self, x_input, nb_classes):
        super(MyModel, self).__init__(nb_classes=nb_classes)
        with slim.arg_scope(inception.inception_v1_arg_scope()):
            _, self.end_points = inception.inception_v1(
                x_input, num_classes=self.nb_classes, is_training=False)
            
    def get_probs(self, x_input):
        return {self.O_LOGITS: self.end_points['Logits'],
              self.O_PROBS: self.end_points['Predictions'].op.inputs[0]}

with tf.Graph().as_default():
    x_input = tf.placeholder(tf.float32, shape=batch_shape)
    model = MyModel(x_input, nb_classes) 
    with tf.Session() as sess:
        mim = MomentumIterativeMethod(model, sess=sess)
        x_adv = mim.generate(x_input, **attack_params)

```

> C:\ProgramData\Miniconda3\lib\site-packages\cleverhans\attacks\__init__.py in body(i, ax, m)
    798 
    799       # Normalize current gradient and add it to the accumulated gradient
--> 800       red_ind = list(xrange(1, len(grad.get_shape())))
    801       avoid_zero_div = tf.cast(1e-12, grad.dtype)
    802       grad = grad / tf.maximum(

AttributeError: 'NoneType' object has no attribute 'get_shape'

Why I raised this question, because I like to load graph and weight from pre-trained model,  and attack the same model with different attack methods without loading the model again, is it possible?
following approach failed because above error
```
model = MyModel()
load_weight()
with tf.Session() as sess:
    attack1 = MomentumIterativeMethod(model, sess)
    attack1.generate(x)
    attack2 = FastGradientMethod(model, sess)
    attack2.generate(x)
```

**Comment by npapernot** [comment]
The reason you cannot prepare the graph in init is that many attacks need to get the output tensor of the model for different inputs (for instance, iterative attacks need to get the model's output on the current modified input after each iteration). 

I am closing this because this is neither a bug nor a feature request. Please use StackOverflow as indicated in the issue templates. Thanks!
